#ifndef CNC_CONFIG_COMMON_H
#define CNC_CONFIG_COMMON_H

	#define CncToolMagazine_SECTION_NAME					"CncWork_ToolMagazine"
	#define CncToolMagazineParam_SECTION_NAME				"CncWork_ToolMagazineParameter"
	#define CncToolMagazineParam_USE_DEF_TOOL				"USE_DEFAULT_TOOL"
	#define CncToolMagazineParam_MAP_DEF_TOOL_TO			"MAP_DEFAULT_TOOL_TO"
		
	#define Attribute_SEC_NAME								"SEC_NAME"
	#define Attribute_READONLY								"READONLY"

	#define CncConfig_ACCEL_FUNC_PARA_A						"Cnc_Config|ACCEL_FUNC_PARA_A"
	#define CncConfig_ACCEL_FUNC_PARA_B						"Cnc_Config|ACCEL_FUNC_PARA_B"
	#define CncConfig_ACCEL_FUNC_PARA_C						"Cnc_Config|ACCEL_FUNC_PARA_C"
	
	#define CncConfig_DEACCEL_FUNC_PARA_A					"Cnc_Config|DEACCEL_FUNC_PARA_A"
	#define CncConfig_DEACCEL_FUNC_PARA_B					"Cnc_Config|DEACCEL_FUNC_PARA_B"
	#define CncConfig_DEACCEL_FUNC_PARA_C					"Cnc_Config|DEACCEL_FUNC_PARA_C"
	
	#define CncConfig_MAX_SPEED_XYZ_MM_MIN					"Cnc_Config|MAX_SPEED_XYZ_MM_MIN"
	#define CncConfig_DEF_SPEED_MODE_XYZ					"Cnc_Config|DEF_SPEED_MODE_XYZ"
	#define CncConfig_DEF_RAPID_SPEED_PERCENT 				"Cnc_Config|DEF_RAPID_SPEED_PEERCENT"
	#define CncConfig_DEF_WORK_SPEED_PERCENT				"Cnc_Config|DEF_WORK_SPEED_PERCENT"
	#define CncConfig_DEF_RAPID_SPEED_MM_MIN 				"Cnc.Config|DEF_RAPID_SPEED_MM_SEC"
	#define CncConfig_DEF_WORK_SPEED_MM_MIN 				"Cnc.Config|DEF_WORK_SPEED_MM_SEC"
	
	#define CncConfig_MAX_DIMENSION_X 						"Cnc_Config|MAX_DIMENSION_X"
	#define CncConfig_MAX_DIMENSION_Y 						"Cnc_Config|MAX_DIMENSION_Y"
	#define CncConfig_MAX_DIMENSION_Z 						"Cnc_Config|MAX_DIMENSION_Z"
	#define CncConfig_MAX_DIMENSION_H 						"Cnc_Config|MAX_DIMENSION_H"
	#define CncConfig_STEPS_X 								"Cnc_Config|STEPS_X"
	#define CncConfig_STEPS_Y 								"Cnc_Config|STEPS_Y"
	#define CncConfig_STEPS_Z								"Cnc_Config|STEPS_Z"
	#define CncConfig_STEPS_H								"Cnc_Config|STEPS_H"
	#define CncConfig_PITCH_X 								"Cnc_Config|PITCH_X"
	#define CncConfig_PITCH_Y 								"Cnc_Config|PITCH_Y"
	#define CncConfig_PITCH_Z 								"Cnc_Config|PITCH_Z"
	#define CncConfig_PITCH_H 								"Cnc_Config|PITCH_H"
	#define CncConfig_MULTIPLIER_X 							"Cnc_Config|MULTIPLIER_X"
	#define CncConfig_MULTIPLIER_Y 							"Cnc_Config|MULTIPLIER_Y"
	#define CncConfig_MULTIPLIER_Z 							"Cnc_Config|MULTIPLIER_Z"
	#define CncConfig_PULSE_WIDTH_HIGH_X					"Cnc_Config|PULSE_WIDTH_HIGH_X"
	#define CncConfig_PULSE_WIDTH_HIGH_Y					"Cnc_Config|PULSE_WIDTH_HIGH_Y"
	#define CncConfig_PULSE_WIDTH_HIGH_Z					"Cnc_Config|PULSE_WIDTH_HIGH_Z"
	#define CncConfig_PULSE_WIDTH_HIGH_H					"Cnc_Config|PULSE_WIDTH_HIGH_H"

	#define CncRuntime_DISPLAY_FACT_X 						"#|CncRuntime|DISPLAY_FACT_X"
	#define CncRuntime_DISPLAY_FACT_Y 						"#|CncRuntime|DISPLAY_FACT_Y"
	#define CncRuntime_DISPLAY_FACT_Z 						"#|CncRuntime|DISPLAY_FACT_Z"
	#define CncRuntime_DISPLAY_FACT_3D_X 					"#|CncRuntime|DISPLAY_FACT_3D_X"
	#define CncRuntime_DISPLAY_FACT_3D_Y					"#|CncRuntime|DISPLAY_FACT_3D_Y"
	#define CncRuntime_DISPLAY_FACT_3D_Z 					"#|CncRuntime|DISPLAY_FACT_3D_Z"
	#define CncRuntime_CALCULATION_FACT_X 					"#|CncRuntime|CALCULATION_FACT_X"
	#define CncRuntime_CALCULATION_FACT_Y 					"#|CncRuntime|CALCULATION_FACT_Y"
	#define CncRuntime_CALCULATION_FACT_Z 					"#|CncRuntime|CALCULATION_FACT_Z"
	
	/*
	#define CncRuntime_Z_MAX_DURATIONS						"#|CncRuntime|Z_MAX_DURATIONS"
	#define CncRuntime_Z_WORKPIECE_OFFSET					"#|CncRuntime|Z_WORKPIECE_OFFSET"
	#define CncRuntime_Z_MAX_DURATION_THICKNESS				"#|CncRuntime|Z_MAX_DURATION_THICKNESS"
	#define CncRuntime_Z_CALCULATED_DURATIONS				"#|CncRuntime|Z_CALCULATED_DURATIONS"
	#define CncRuntime_Z_CURRENT_Z_DISTANCE					"#|CncRuntime|Z_CURRENT_Z_DISTANCE"
	#define CncRuntime_Z_WORKPIECE_INCLUDED					"#|CncRuntime|Z_WORKPIECE_INCLUDED"
	#define CncRuntime_Z_DURATION_THICKNESS					"#|CncRuntime|Z_DURATION_THICKNESS"
	*/
	#define CncApplication_SHOW_SPLASH_SCREEN 				"CncApplication|SHOW_SPLASH_SCREEN"
	#define CncApplication_DEF_DISPLAY_UNIT 				"CncApplication|DEF_DISPLAY_UNIT"
	#define CncApplication_AUTO_CONNECT 					"CncApplication|AUTO_CONNECT"
	#define CncApplication_AUTO_OPEN_LAST 					"CncApplication|AUTO_OPEN_LAST"
	#define CncApplication_AUTO_PROCESS 					"CncApplication|AUTO_PROCESS"
	#define CncApplication_AUTO_OPEN_OGL_OBSERVER			"CncApplication|AUTO_OPEN_OGL_OBSERVER"
	#define CncApplication_SHOW_TEST_MENU 					"CncApplication|SHOW_TEST_MENU"
	#define CncApplication_CONFIRMATION_MODE				"CncApplication|CONFIRMATION_MODE"
	#define CncApplication_USE_MAIN_PREVIEW					"CncApplication|USE_MAIN_PREVIEW"
	#define CncApplication_USE_MONITOR_PREVIEW				"CncApplication|USE_MONITOR_PREVIEW"
	#define CncApplication_Com_DEFAULT_PORT 				"CncApplication_Port|DEFAULT_PORT"
	#define CncApplication_Tpl_DEFAULT_TEST_DIRECTORY		"CncApplication_Template|OSD_DEFAULT_TEST_DIRECTORY"
	#define CncApplication_Tpl_DEFAULT_DIRECTORY			"CncApplication_Template|OSD_DEFAULT_DIRECTORY"
	#define CncApplication_Tpl_DEFAULT_FILE 				"CncApplication_Template|OSD_DEFAULT_FILE"
	#define CncApplication_Tool_FILE_BROWSER				"CncApplication_Tools|OSD_FILE_BROWSER"
	#define CncApplication_Tool_SVG_FILE_VIEWER 			"CncApplication_Tools|OSD_SVG_FILE_VIEWER"
	#define CncApplication_Tool_BIN_FILE_VIEWER 			"CncApplication_Tools|OSD_BIN_FILE_VIEWER"
	#define CncApplication_Tool_GCODE_FILE_VIEWER 			"CncApplication_Tools|OSD_GCODE_FILE_VIEWER"
	#define CncApplication_Tool_XML_FILE_VIEWER 			"CncApplication_Tools|OSD_XML_FILE_VIEWER"
	#define CncApplication_Tool_BROWSER					 	"CncApplication_Tools|OSD_BROWSER"
	#define CncApplication_Tool_EXTERNAL_EDITOR				"CncApplication_Tools|OSD_EXTERNAL_EDITOR"
	#define CncApplication_Tool_EXTERNAL_HEX_EDITOR			"CncApplication_Tools|OSD_EXTERNAL_HEX_EDITOR"
	#define CncApplication_Tool_VEUSZ_PLOTTER				"CncApplication_Tools|OSD_VEUSZ_PLOTTER"
	#define CncApplication_Tool_PY_CAM 						"CncApplication_Tools|OSD_PY_CAM"
	
	#define CncSvg_Parser_REVERSE_Y_AXIS					"CncSvg_Parser|CONVERT_TO_RIGHT_HAND"
	#define CncSvg_Parser_CONSIDER_VIEWBOX					"CncSvg_Parser|CONSIDER_VIEWBOX"
	#define CncSvg_Parser_DEFAULT_VIEW_TYPE					"CncSvg_Parser|DEFAULT_VIEW_TYPE"
	#define CncSvg_Parser_USE_COLOUR_SCHEME					"CncSvg_Parser|USE_COLOUR_SCHEME"
	#define CncSvg_Parser_MAX_THICKNESS_CROSS				"CncSvg_Parser|MAX_THICKNESS_PER_CROSSING"
	#define CncSvg_Parser_SUREFACE_Z_OFFSET					"CncSvg_Parser|SUREFACE_Z_OFFSET"
	
	#define CncGCode_Parser_PLACEHOLDER						"CncGCode_Parser|CGODE_PLACEHOLDER"
	
	#define CncWork_Ctl_ARTIFICIALLY_STEP_DELAY				"#|CncWork_Controller|ARTIFICIALLY_STEP_DELAY"
	#define CncWork_Ctl_REPLY_THRESHOLD_METRIC				"CncWork_Controller|REPLY_THRESHOLD_METRIC"
	#define CncWork_Ctl_REPLY_THRESHOLD_STEPS				"CncWork_Controller|REPLY_THRESHOLD_STEPS"
	#define CncWork_Ctl_AVOID_DUP_SETTER_VALUES				"CncWork_Controller|AVOID_DUP_SETTER_VALUES"
	#define CncWork_Ctl_SIMULATE_MILLING_WITH_SOUND			"CncWork_Controller|AVOID_SIMULATE_MILLING_WITH_SOUND"
	#define CncWork_Ctl_REQUEST_IDLE_REQUESTS				"CncWork_Controller|REQUEST_IDLE_REQUESTS"
	#define CncWork_Ctl_INTERRUPT_BY_POS_OUTOFRANGE			"CncWork_Controller|INTERRUPT_BY_POS_OUTOFRANGE"
	#define CncWork_Ctl_INVERSE_CTL_DIRECTION_X				"CncWork_Controller|INVERSE_CTL_DIRECTION_X"
	#define CncWork_Ctl_INVERSE_CTL_DIRECTION_Y				"CncWork_Controller|INVERSE_CTL_DIRECTION_Y"
	#define CncWork_Ctl_INVERSE_CTL_DIRECTION_Z				"CncWork_Controller|INVERSE_CTL_DIRECTION_Z"
	#define CncWork_Ctl_PRE_PROSSOR_RENDER_RESOLUTION		"CncWork_Controller|PRE_PROSSOR_RENDER_RESOLUTION"
	#define CncWork_Ctl_PRE_PROSSOR_MAX_XY_PITCH			"CncWork_Controller|PRE_PROSSOR_MAX_XY_PITCH"
	#define CncWork_Ctl_PRE_PROSSOR_MAX_Z_PITCH				"CncWork_Controller|PRE_PROSSOR_MAX_Z_PITCH"
	#define CncWork_Ctl_PRE_PROSSOR_ANALYSE					"CncWork_Controller|PRE_PROSSOR_ANALYSE"
	#define CncWork_Ctl_PRE_PROSSOR_SKIP_EMPTY				"CncWork_Controller|PRE_PROSSOR_SKIP_EMPTY"
	#define CncWork_Ctl_PRE_PROSSOR_COMBINE_MOVES			"CncWork_Controller|PRE_PROSSOR_COMBINE_MOVES"
	#define CncWork_Ctl_PRE_PROSSOR_USE_OPERATING_TRACE		"CncWork_Controller|PRE_PROSSOR_USE_OPERATING_TRACE"
	#define CncWork_Ctl_PRE_PROSSOR_CNT_PATH_LIST_ENTRIES	"CncWork_Controller|PRE_PROSSOR_CNT_PATH_LIST_ENTRIES"
	#define CncWork_Ctl_PRE_PROSSOR_CNT_SEQUENCE_MOVES		"CncWork_Controller|PRE_PROSSOR_CNT_SEQUENCE_MOVES"
	
	#define CncWork_Ctl_TOUCHBLOCK_Z_THICKNESS				"CncWork_Controller|TOUCHBLOCK_Z_THICKNESS"
	#define CncWork_Ctl_TOUCHBLOCK_X_CHEEK_THICKNESS		"CncWork_Controller|TOUCHBLOCK_X_CHEEK_THICKNESS"
	#define CncWork_Ctl_TOUCHBLOCK_Y_CHEEK_THICKNESS		"CncWork_Controller|TOUCHBLOCK_Y_CHEEK_THICKNESS"
	
	#define CncWork_Ctl_CAMERA_SUPPORT						"CncWork_Controller|CAMERA_SUPPORT"
	#define CncWork_Ctl_CAMERA_DEVICE_ID					"CncWork_Controller|CAMERA_DEVICE_ID"
	#define CncWork_Ctl_CAMERA_OFFSET_X						"CncWork_Controller|CAMERA_OFFSET_X"
	#define CncWork_Ctl_CAMERA_OFFSET_Y						"CncWork_Controller|CAMERA_OFFSET_Y"
	#define CncWork_Ctl_CAMERA_OFFSET_Z						"CncWork_Controller|CAMERA_OFFSET_Z"
	
	#define CncWork_Ctl_SPINDLE_SPEED_SUPPORT				"CncWork_Controller|SPINDLE_SPEED_SUPPORT"
	#define CncWork_Ctl_SPINDLE_SPEED_STEP_RANGE			"CncWork_Controller|SPINDLE_SPEED_STEP_RANGE"
	#define CncWork_Ctl_SPINDLE_SPEED_MIN					"CncWork_Controller|SPINDLE_SPEED_MIN"
	#define CncWork_Ctl_SPINDLE_SPEED_MAX					"CncWork_Controller|SPINDLE_SPEED_MAX"
	#define CncWork_Ctl_SPINDLE_SPEED_DEFAULT				"CncWork_Controller|SPINDLE_SPEED_DEFAULT"
	
	#define CncTEST_TEST									"CncTest_Test|DUMMY"

#endif