//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef CNCCONTROL_CNCCONTROLERGUI_WXCRAFTER_BASE_CLASSES_H
#define CNCCONTROL_CNCCONTROLERGUI_WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/aui/framemanager.h>
#include <wx/aui/dockart.h>
#include <wx/pen.h>
#include <wx/aui/auibar.h>
#include <map>
#include <wx/menu.h>
#include <wx/stattext.h>
#include <wx/combobox.h>
#include <wx/arrstr.h>
#include <wx/bmpbuttn.h>
#include <wx/toolbar.h>
#include <wx/slider.h>
#include <wx/button.h>
#include <wx/scrolwin.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/imaglist.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/textctrl.h>
#include <wx/checkbox.h>
#include <wx/listbook.h>
#include <wx/treebook.h>
#include <wx/spinctrl.h>
#include <wx/tglbtn.h>
#include <wx/listbox.h>
#include <wx/radiobox.h>
#include <wx/stc/stc.h>
#include <wx/statbmp.h>
#include <wx/dataview.h>
#include <wx/webview.h>
#include "CncSpeedView.h"
#include <wx/toolbook.h>
#include <wx/dirctrl.h>
#include "CncZView.h"
#include <wx/timer.h>
#include <wx/splitter.h>
#include <wx/propgrid/manager.h>
#include <wx/propgrid/property.h>
#include <wx/propgrid/advprops.h>
#include <wx/dialog.h>
#include <wx/bitmap.h>
#include <wx/icon.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class MainFrameBClass : public wxFrame
{
protected:
    wxAuiManager* m_auimgrMain;
    wxAuiToolBar* m_auibarMain;
    std::map<int, wxMenu*> m_dropdownMenus;
    wxStaticText* m_staticText1842;
    wxComboBox* m_portSelector;
    wxBitmapButton* m_connect;
    wxStaticText* m_staticText752;
    wxComboBox* m_unit;
    wxStaticText* m_staticText1748;
    wxMenu* m_configStepDelayMenu;
    wxMenuItem* m_miCfgStepDelayMin;
    wxMenuItem* m_miCfgStepDelayMax;
    wxMenuItem* m_miCfgSimulateArduino;
    wxMenuItem* m_miCfgCustom;
    wxSlider* m_stepDelay;
    wxStaticText* m_stepDelayValue;
    wxBitmapButton* m_rcReset;
    wxMenu* m_rcConfigMenu;
    wxMenuItem* m_miRcRun;
    wxMenuItem* m_miRcDebug;
    wxMenuItem* m_menuItem2028;
    wxMenuItem* m_miRcPreprocessing;
    wxMenuItem* m_miRcUserAgent;
    wxMenuItem* m_miRcSpooling;
    wxBitmapButton* m_rcRun;
    wxBitmapButton* m_rcPause;
    wxBitmapButton* m_rcNextPath;
    wxBitmapButton* m_rcNextStep;
    wxBitmapButton* m_rcFinish;
    wxBitmapButton* m_rcStop;
    wxBitmapButton* m_controlerPause;
    wxButton* m_btnEmergenyStop;
    wxScrolledWindow* m_scrollWinMain;
    wxFlexGridSizer* flexGridSizer434;
    wxNotebook* m_mainNotebook;
    wxPanel* m_panelReference;
    wxFlexGridSizer* flexGridSizer1885;
    wxFlexGridSizer* flexGridSizer1393;
    wxFlexGridSizer* flexGridSizer777;
    wxStaticText* m_staticText779;
    wxStaticLine* m_staticLine783;
    wxFlexGridSizer* flexGridSizer547;
    wxStaticText* m_staticText821;
    wxSpinButton* m_spinButtonX;
    wxStaticText* m_staticText63169;
    wxSpinButton* m_spinButtonY;
    wxTextCtrl* m_moveXYAxisCtl;
    wxStaticText* m_staticText823;
    wxStaticText* m_staticText6316;
    wxStaticText* m_staticText825;
    wxStaticText* m_staticText827;
    wxStaticText* m_staticText631;
    wxStaticText* m_staticText832;
    wxStaticText* m_staticText834;
    wxSpinButton* m_spinButtonZ;
    wxTextCtrl* m_moveZAxisCtl;
    wxStaticText* m_staticText830;
    wxStaticText* m_staticText836;
    wxFlexGridSizer* flexGridSizer1390;
    wxCheckBox* m_includingWpt;
    wxButton* m_setZero;
    wxFlexGridSizer* flexGridSizer1163;
    wxFlexGridSizer* flexGridSizer1152;
    wxStaticText* m_staticText1156;
    wxStaticLine* m_staticLine1158;
    wxFlexGridSizer* flexGridSizer1165;
    wxStaticText* m_staticText1171;
    wxStaticText* m_staticText1173;
    wxComboBox* m_homeDefintion;
    wxButton* m_moveHome;
    wxStaticLine* m_staticLine2177;
    wxStaticLine* m_staticLine2179;
    wxFlexGridSizer* flexGridSizer2180;
    wxStaticText* m_staticText2182;
    wxComboBox* m_zeroMoveModeXY;
    wxButton* m_moveXYtoZero;
    wxFlexGridSizer* flexGridSizer218027;
    wxStaticText* m_staticText218228;
    wxComboBox* m_zeroMoveModeXYZ;
    wxButton* m_moveXYZtoZero;
    wxFlexGridSizer* flexGridSizer21802730;
    wxStaticText* m_staticText21822831;
    wxComboBox* m_zeroMoveModeZ;
    wxButton* m_moveZtoZero;
    wxStaticLine* m_staticLine2191;
    wxStaticLine* m_staticLine2193;
    wxStaticText* m_staticText1177233;
    wxStaticText* m_staticText11772;
    wxFlexGridSizer* flexGridSizer2439;
    wxButton* m_xToMax;
    wxButton* m_xToMid;
    wxButton* m_xToMin;
    wxFlexGridSizer* flexGridSizer2440;
    wxButton* m_yToMax;
    wxButton* m_yToMid;
    wxButton* m_yToMin;
    wxStaticLine* m_staticLine2195;
    wxStaticLine* m_staticLine2197;
    wxStaticText* m_staticText1175;
    wxStaticText* m_staticText1177;
    wxFlexGridSizer* flexGridSizer2434;
    wxButton* m_zToMax;
    wxButton* m_zToMid;
    wxButton* m_zToMin;
    wxFlexGridSizer* flexGridSizer2435;
    wxButton* m_zToTop;
    wxStaticText* m_staticText2438;
    wxButton* m_zToBottom;
    wxPanel* m_panelSetup;
    wxFlexGridSizer* flexGridSizer1884;
    wxListbook* m_listbook2220;
    wxPanel* m_setupWorkPage;
    wxFlexGridSizer* flexGridSizer2218;
    wxFlexGridSizer* flexGridSizer961;
    wxStaticText* m_staticText7791;
    wxStaticLine* m_staticLine9572;
    wxFlexGridSizer* flexGridSizer963;
    wxStaticText* m_staticText569;
    wxTextCtrl* m_workpieceThickness;
    wxStaticText* m_staticText1289;
    wxTextCtrl* m_crossingThickness;
    wxStaticLine* m_staticLine3109;
    wxFlexGridSizer* flexGridSizer3107;
    wxStaticText* m_staticText57510;
    wxComboBox* m_cbToolType;
    wxStaticText* m_staticText575;
    wxTextCtrl* m_routerBitDiameter;
    wxStaticLine* m_staticLine3111;
    wxFlexGridSizer* flexGridSizer1423;
    wxStaticText* m_staticText12374;
    wxTextCtrl* m_replyThreshold;
    wxStaticText* m_staticText1517;
    wxComboBox* m_cbStepSignX;
    wxStaticText* m_staticText1519;
    wxComboBox* m_cbStepSignY;
    wxStaticText* m_staticText1479;
    wxComboBox* m_cbUseProceesdSetterList;
    wxStaticText* m_staticText1475;
    wxComboBox* m_cbClearProceesdSetterList;
    wxPanel* m_setupSpeedPage;
    wxFlexGridSizer* flexGridSizer2237;
    wxFlexGridSizer* flexGridSizer96114;
    wxStaticText* m_staticText779125;
    wxStaticLine* m_staticLine957236;
    wxFlexGridSizer* flexGridSizer2793;
    wxStaticText* m_staticText2798;
    wxComboBox* m_cbPreconfiguredSpeedSetups;
    wxStaticLine* m_staticLine9572361;
    wxFlexGridSizer* flexGridSizer1387;
    wxStaticText* m_staticText9241;
    wxTextCtrl* m_maxXYSpeed;
    wxStaticText* m_staticText924;
    wxComboBox* m_flySpeedXY;
    wxStaticText* m_staticText932;
    wxComboBox* m_workSpeedXY;
    wxStaticText* m_staticText1019;
    wxComboBox* m_currentSpeedXY;
    wxFlexGridSizer* flexGridSizer265915;
    wxButton* m_button266116;
    wxStaticLine* m_staticLine3113;
    wxFlexGridSizer* flexGridSizer2241;
    wxStaticText* m_staticText1208;
    wxTextCtrl* m_maxZSpeed;
    wxStaticText* m_staticText92813;
    wxComboBox* m_flySpeedZ;
    wxStaticText* m_staticText1213;
    wxComboBox* m_workSpeedZ;
    wxStaticText* m_staticText101911;
    wxComboBox* m_currentSpeedZ;
    wxFlexGridSizer* flexGridSizer2659;
    wxButton* m_button2661;
    wxPanel* m_setupDimPage;
    wxFlexGridSizer* flexGridSizer2234;
    wxFlexGridSizer* flexGridSizer9611;
    wxStaticText* m_staticText77912;
    wxStaticLine* m_staticLine95723;
    wxFlexGridSizer* flexGridSizer1380;
    wxStaticText* m_staticText854;
    wxTextCtrl* m_maxXDimension;
    wxStaticText* m_staticText856;
    wxTextCtrl* m_maxYDimension;
    wxStaticText* m_staticText85611;
    wxTextCtrl* m_maxZDimension;
    wxPanel* m_setupSVGPage;
    wxFlexGridSizer* flexGridSizer2229;
    wxFlexGridSizer* flexGridSizer9613;
    wxStaticText* m_staticText77914;
    wxStaticLine* m_staticLine95725;
    wxFlexGridSizer* flexGridSizer9636;
    wxStaticText* m_staticText1237;
    wxComboBox* m_cbSvgZoom;
    wxStaticText* m_staticText1261;
    wxComboBox* m_cbSvgIncludeOriginalPath;
    wxStaticText* m_staticText126111;
    wxComboBox* m_cbSvgFirstCrossing;
    wxFlexGridSizer* flexGridSizer1134;
    wxPanel* m_setupEnvPage;
    wxFlexGridSizer* flexGridSizer2232;
    wxFlexGridSizer* flexGridSizer1873;
    wxStaticText* m_staticText1880;
    wxStaticLine* m_staticLine2226;
    wxTextCtrl* m_envrionmentInfo;
    wxPanel* m_setupApp;
    wxFlexGridSizer* flexGridSizer2627;
    wxFlexGridSizer* flexGridSizer96111;
    wxStaticText* m_staticText779122;
    wxStaticLine* m_staticLine957233;
    wxFlexGridSizer* flexGridSizer26351;
    wxFlexGridSizer* flexGridSizer963642;
    wxStaticText* m_staticText123753;
    wxComboBox* m_cbRunMotionMonitorMode;
    wxFlexGridSizer* flexGridSizer2635;
    wxFlexGridSizer* flexGridSizer96364;
    wxStaticText* m_staticText12375;
    wxComboBox* m_cbRunConfirmationMode;
    wxPanel* m_panelTesting;
    wxFlexGridSizer* flexGridSizer2205;
    wxTreebook* m_treebookTest;
    wxPanel* m_testIntervalPage;
    wxFlexGridSizer* flexGridSizer2089;
    wxFlexGridSizer* flexGridSizer2157;
    wxStaticText* m_staticText2117;
    wxStaticLine* m_staticLine2253;
    wxComboBox* m_testIntervalMode;
    wxFlexGridSizer* flexGridSizer2103;
    wxStaticText* m_staticText2105;
    wxStaticText* m_staticText2107;
    wxStaticText* m_staticText2109;
    wxStaticText* m_staticText2149;
    wxStaticText* m_staticText2115;
    wxStaticText* m_staticText2165;
    wxStaticLine* m_staticLine2111;
    wxFlexGridSizer* flexGridSizer2091;
    wxStaticText* m_testAxisX;
    wxSpinCtrl* m_testCountX;
    wxTextCtrl* m_testDistanceX;
    wxStaticText* m_staticText2101;
    wxComboBox* m_testFirstX;
    wxStaticText* m_staticText2151;
    wxCheckBox* m_testModeX;
    wxStaticText* m_testDurationCounterX;
    wxFlexGridSizer* flexGridSizer209111;
    wxStaticText* m_testAxisY;
    wxSpinCtrl* m_testCountY;
    wxTextCtrl* m_testDistanceY;
    wxStaticText* m_staticText210115;
    wxComboBox* m_testFirstY;
    wxStaticText* m_staticText215123;
    wxCheckBox* m_testModeY;
    wxStaticText* m_testDurationCounterY;
    wxFlexGridSizer* flexGridSizer20911117;
    wxStaticText* m_testAxisZ;
    wxSpinCtrl* m_testCountZ;
    wxTextCtrl* m_testDistanceZ;
    wxStaticText* m_staticText21011521;
    wxComboBox* m_testFirstZ;
    wxStaticText* m_staticText215124;
    wxCheckBox* m_testModeZ;
    wxStaticText* m_testDurationCounterZ;
    wxPanel* m_testDimensions;
    wxFlexGridSizer* flexGridSizer2319;
    wxFlexGridSizer* flexGridSizer21573;
    wxStaticText* m_staticText21174;
    wxStaticLine* m_staticLine22535;
    wxFlexGridSizer* flexGridSizer2375;
    wxStaticText* m_staticText2377;
    wxStaticText* m_staticText2418;
    wxStaticText* m_staticText2381;
    wxStaticText* m_staticText2379;
    wxStaticText* m_staticText2383;
    wxCheckBox* m_testDimTakeOverAndSave;
    wxStaticLine* m_staticLine2385;
    wxFlexGridSizer* flexGridSizer2363;
    wxStaticText* m_testDimAxisX;
    wxCheckBox* m_testDimModeX;
    wxCheckBox* m_testDimMinX;
    wxCheckBox* m_testDimMaxX;
    wxTextCtrl* m_testDimResultX;
    wxStaticText* m_staticText2431;
    wxCheckBox* m_testDimResultStateX;
    wxButton* m_testDimTakeX;
    wxFlexGridSizer* flexGridSizer23631;
    wxStaticText* m_testDimAxisY;
    wxCheckBox* m_testDimModeY;
    wxCheckBox* m_testDimMinY;
    wxCheckBox* m_testDimMaxY;
    wxTextCtrl* m_testDimResultY;
    wxStaticText* m_testDimUnitX6;
    wxCheckBox* m_testDimResultStateY;
    wxButton* m_testDimTakeY;
    wxFlexGridSizer* flexGridSizer23637;
    wxStaticText* m_testDimAxisZ;
    wxCheckBox* m_testDimModeZ;
    wxCheckBox* m_testDimMinZ;
    wxCheckBox* m_testDimMaxZ;
    wxTextCtrl* m_testDimResultZ;
    wxStaticText* m_testDimUnitX12;
    wxCheckBox* m_testDimResultStateZ;
    wxButton* m_testDimTakeZ;
    wxStaticLine* m_staticLine2429;
    wxButton* m_testDimTakeAll;
    wxPanel* m_testLimitPage;
    wxFlexGridSizer* flexGridSizer2249;
    wxFlexGridSizer* flexGridSizer21571;
    wxStaticText* m_staticText21172;
    wxStaticLine* m_staticLine22533;
    wxFlexGridSizer* flexGridSizer2269;
    wxToggleButton* m_testToggleEndSwitch;
    wxPanel* m_testToolPage;
    wxFlexGridSizer* flexGridSizer2251;
    wxFlexGridSizer* flexGridSizer215715;
    wxStaticText* m_staticText211726;
    wxStaticLine* m_staticLine225337;
    wxFlexGridSizer* flexGridSizer2275;
    wxToggleButton* m_testToggleTool;
    wxPanel* m_ctrlTestSuite;
    wxFlexGridSizer* flexGridSizer24722;
    wxFlexGridSizer* flexGridSizer21573253;
    wxFlexGridSizer* flexGridSizer25094;
    wxStaticText* m_staticText21174365;
    wxTextCtrl* m_ctrlTestSelectedId;
    wxStaticLine* m_staticLine22535477;
    wxFlexGridSizer* flexGridSizer24808;
    wxStaticText* m_staticText25139;
    wxScrolledWindow* m_scrollWin2571;
    wxFlexGridSizer* flexGridSizer2573;
    wxListBox* m_ctrlTestSelection;
    wxStaticText* m_staticText251911;
    wxTextCtrl* m_ctrlTestDescription;
    wxFlexGridSizer* flexGridSizer248413;
    wxStaticText* m_staticText2486121314;
    wxTextCtrl* m_ctrlTestParam1;
    wxStaticText* m_staticText24861216;
    wxTextCtrl* m_ctrlTestParam2;
    wxStaticText* m_staticText24861418;
    wxTextCtrl* m_ctrlTestParam3;
    wxStaticText* m_staticText24861520;
    wxTextCtrl* m_ctrlTestParam4;
    wxStaticText* m_staticText248622;
    wxTextCtrl* m_ctrlTestParam5;
    wxPanel* m_panelManually;
    wxFlexGridSizer* flexGridSizer862;
    wxFlexGridSizer* flexGridSizer418;
    wxFlexGridSizer* flexGridSizer1169;
    wxFlexGridSizer* flexGridSizer2081;
    wxCheckBox* m_checkManuallyXY;
    wxStaticText* m_staticText1160;
    wxStaticLine* m_staticLine1162;
    wxFlexGridSizer* flexGridSizer1522;
    wxRadioBox* m_mmRadioCoordinates;
    wxFlexGridSizer* flexGridSizer1523;
    wxStaticText* m_staticText799;
    wxComboBox* m_metricZ;
    wxFlexGridSizer* flexGridSizer1590;
    wxFlexGridSizer* flexGridSizer7893;
    wxStaticText* m_staticText793;
    wxButton* m_minManuallyXSlider;
    wxTextCtrl* m_metricX;
    wxButton* m_maxManuallyXSlider;
    wxButton* m_zeroManuallyXSlider;
    wxButton* m_signManuallyXSlider;
    wxStaticText* m_mmUnitX;
    wxSlider* m_xManuallySlider;
    wxFlexGridSizer* flexGridSizer1591;
    wxFlexGridSizer* flexGridSizer7894;
    wxStaticText* m_staticText797;
    wxButton* m_minManuallyYSlider;
    wxTextCtrl* m_metricY;
    wxButton* m_maxManuallyYSlider;
    wxButton* m_zeroManuallyYSlider;
    wxButton* m_signManuallyYSlider;
    wxStaticText* m_mmUnitY;
    wxSlider* m_yManuallySlider;
    wxStaticText* m_staticText2073;
    wxStaticLine* m_staticLine2047;
    wxFlexGridSizer* flexGridSizer2078;
    wxCheckBox* m_checkManuallyZ;
    wxStaticText* m_staticText2075;
    wxFlexGridSizer* flexGridSizer15911;
    wxFlexGridSizer* flexGridSizer78942;
    wxStaticText* m_staticText7973;
    wxButton* m_minManuallyZSlider;
    wxTextCtrl* m_metricZEdit;
    wxButton* m_maxManuallyZSlider;
    wxButton* m_zeroManuallyZSlider;
    wxButton* m_signManuallyZSlider;
    wxStaticText* m_mmUnitZ;
    wxSlider* m_zManuallySlider;
    wxPanel* m_panelTemplateContent;
    wxFlexGridSizer* flexGridSizer706;
    wxFlexGridSizer* flexGridSizer1368;
    wxButton* m_openSourceExtern;
    wxButton* m_openSvgExtern;
    wxButton* m_btPathGenerator;
    wxButton* m_saveTemplate;
    wxButton* m_reloadTemplate;
    wxBitmapToggleButton* m_btSvgToggleWordWrap;
    wxBitmapToggleButton* m_previewErrorInfo;
    wxNotebook* m_templateNotebook;
    wxPanel* m_panelTplEdit;
    wxFlexGridSizer* flexGridSizer1294;
    wxStyledTextCtrl* m_stcFileContent;
    wxFlexGridSizer* flexGridSizer1809;
    wxBitmapToggleButton* m_tbCaseSensitive;
    wxBitmapToggleButton* m_tbWholeWord;
    wxBitmapToggleButton* m_tbRegEx;
    wxBitmapToggleButton* m_tbHighLight;
    wxStaticBitmap* m_svgEditSearchState;
    wxComboBox* m_svgEditSearch;
    wxButton* m_svgEditFind;
    wxButton* m_svgEditFindPrev;
    wxFlexGridSizer* flexGridSizer713;
    wxStaticText* m_filePosition;
    wxTextCtrl* m_svgEditStatus;
    wxStaticText* m_editMode;
    wxPanel* m_panelTplUserAgent;
    wxFlexGridSizer* flexGridSizer1506;
    wxFlexGridSizer* flexGridSizer1488;
    wxFlexGridSizer* flexGridSizer1490;
    wxStaticText* m_staticText1498;
    wxDataViewListCtrl* m_dvListCtrlSvgUAInboundPathList;
    wxStaticText* m_staticText14983;
    wxDataViewListCtrl* m_dvListCtrlSvgUAUseDirective;
    wxFlexGridSizer* flexGridSizer1492;
    wxStaticText* m_staticText1500;
    wxDataViewListCtrl* m_dvListCtrlSvgUADetailInfo;
    wxTextCtrl* m_selectedUAInfo;
    wxPanel* m_panelTplDebugger;
    wxFlexGridSizer* flexGridSizer1338;
    wxFlexGridSizer* flexGridSizer1565;
    wxStaticText* m_staticText1370;
    wxStaticText* m_staticText1571;
    wxStaticText* m_debugPhase;
    wxDataViewListCtrl* m_dvListCtrlSvgDebuggerInfoBase;
    wxFlexGridSizer* flexGridSizer1362;
    wxStaticText* m_staticText1372;
    wxStaticText* m_staticText1374;
    wxDataViewListCtrl* m_dvListCtrlSvgDebuggerInfoPath;
    wxDataViewListCtrl* m_dvListCtrlSvgDebuggerInfoDetail;
    wxFlexGridSizer* flexGridSizer1354;
    wxTextCtrl* m_svgDebuggerKey;
    wxTextCtrl* m_svgDebuggerValue;
    wxPanel* m_panelTplPreview;
    wxFlexGridSizer* flexGridSizer692;
    wxStaticText* m_svgFilePreviewHint;
#if wxUSE_WEBVIEW
    wxWebView* m_svgPreview;
#endif // wxUSE_WEBVIEW

    wxPanel* m_panelSpeed;
    wxFlexGridSizer* flexGridSizer28011;
    wxStaticText* m_staticText28052;
    CncSpeedView* m_speedView;
    wxScrolledWindow* m_scrollWinFile;
    wxFlexGridSizer* flexGridSizer1628;
    wxToolbook* m_templateToolbook;
    wxPanel* m_lruPanel;
    wxFlexGridSizer* flexGridSizer1642;
    wxStaticText* m_staticText1644;
    wxListBox* m_lruList;
    wxPanel* m_stdPanel;
    wxFlexGridSizer* flexGridSizer2599;
    wxFlexGridSizer* flexGridSizer1636;
    wxButton* m_btDefaultDir;
    wxButton* m_btCurrentFile;
    wxFlexGridSizer* flexGridSizer1645;
    wxStaticText* m_staticText1647;
    wxGenericDirCtrl* m_dirCtrl;
    wxScrolledWindow* m_scrollWinLogger;
    wxFlexGridSizer* flexGridSizer869;
    wxToolbook* m_loggerToolbook;
    wxPanel* m_panel3157;
    wxFlexGridSizer* flexGridSizer3158;
    wxFlexGridSizer* flexGridSizer1863;
    wxBitmapButton* m_clearLogger;
    wxBitmapButton* m_freezeLogger;
    wxBitmapButton* m_copyLogger;
    wxCheckBox* m_showLoggerOnDemand;
    wxFlexGridSizer* flexGridSizer2520;
    wxTextCtrl* m_logger;
    wxTextCtrl* m_tmpTraceInfo;
    wxScrolledWindow* m_statusBar;
    wxFlexGridSizer* flexGridSizer436;
    wxStaticText* m_staticText3952;
    wxTextCtrl* m_cmdCount;
    wxStaticText* m_staticText395;
    wxTextCtrl* m_cmdDuration;
    wxStaticLine* m_staticLine602;
    wxTextCtrl* m_inputFileName;
    wxStaticLine* m_staticLine6801;
    wxStaticText* m_svgParseMode;
    wxPanel* m_activityPanel;
    wxStaticLine* m_staticLine680;
    wxStaticText* LableX;
    wxTextCtrl* m_xAxis;
    wxTextCtrl* m_xAxisCtl;
    wxStaticText* LabelY;
    wxTextCtrl* m_yAxis;
    wxTextCtrl* m_yAxisCtl;
    wxStaticText* LableZ;
    wxTextCtrl* m_zAxis;
    wxTextCtrl* m_zAxisCtl;
    wxStaticLine* m_staticLine60234;
    wxStaticText* m_staticText1196;
    wxStaticText* m_xMinLimit;
    wxStaticText* m_xMaxLimit;
    wxStaticText* m_yMinLimit;
    wxStaticText* m_yMaxLimit;
    wxStaticText* m_zMinLimit;
    wxStaticText* m_zMaxLimit;
    wxStaticLine* m_staticLine602341;
    wxStaticText* m_staticText2199;
    wxStaticBitmap* m_refPosTrafficLight;
    wxStaticLine* m_staticLine6023412;
    wxScrolledWindow* m_scrollOutbound;
    wxFlexGridSizer* flexGridSizer649;
    wxNotebook* m_outboundNotebook;
    wxPanel* m_cncParameters;
    wxFlexGridSizer* flexGridSizer1076;
    wxListbook* m_notebookConfig;
    wxPanel* m_panel2601;
    wxFlexGridSizer* flexGridSizer2603;
    wxStaticText* m_staticText11481;
    wxDataViewListCtrl* m_dvListCtrlConfigSummary;
    wxFlexGridSizer* flexGridSizer2609;
    wxButton* m_btCancelRun;
    wxButton* m_btConfirmRun;
    wxPanel* m_cncSetters;
    wxFlexGridSizer* flexGridSizer1142;
    wxStaticText* m_staticText1148;
    wxFlexGridSizer* flexGridSizer1471;
    wxStaticText* m_staticText1150;
    wxButton* m_button1473;
    wxDataViewListCtrl* m_dvListCtrlLastSetters;
    wxDataViewListCtrl* m_dvListCtrlProcessedSetters;
    wxPanel* m_cncConfiguration;
    wxFlexGridSizer* flexGridSizer901;
    wxStaticText* m_staticText1283;
    wxStaticText* m_staticText1281;
    wxDataViewListCtrl* m_dvListCtrlStatic;
    wxDataViewListCtrl* m_dvListCtrlDynamic;
    wxPanel* m_controllerConfiguration;
    wxFlexGridSizer* flexGridSizer1306;
    wxFlexGridSizer* flexGridSizer1311;
    wxStaticText* m_staticText12831;
    wxButton* m_btRequestCtlConfig;
    wxDataViewListCtrl* m_dvListCtrlControllerConfig;
    wxPanel* m_controllerPinReport;
    wxFlexGridSizer* flexGridSizer13061;
    wxFlexGridSizer* flexGridSizer13112;
    wxStaticText* m_staticText128313;
    wxButton* m_btRequestCtlPins;
    wxDataViewListCtrl* m_dvListCtrlControllerPins;
    wxPanel* m_conrollerMessages;
    wxFlexGridSizer* flexGridSizer2577;
    wxFlexGridSizer* flexGridSizer2586;
    wxStaticText* m_staticText1283132;
    wxButton* m_btClearMsgHistory;
    wxTextCtrl* m_controllerMsgHistory;
    wxPanel* m_controllerErrorInfo;
    wxFlexGridSizer* flexGridSizer13062;
    wxFlexGridSizer* flexGridSizer13113;
    wxStaticText* m_staticText128314;
    wxButton* m_btRequestCtlErrorInfo;
    wxDataViewListCtrl* m_dvListCtrlControllerErrorInfo;
    wxPanel* m_outPanel;
    wxFlexGridSizer* flexGridSizer1042;
    wxFlexGridSizer* flexGridSizer1046;
    wxStaticText* m_staticText1048;
    CncZView* m_zView;
    wxStaticText* m_infoToolDiameter;
    wxStaticBitmap* m_staticBitmap2401;
    wxFlexGridSizer* flexGridSizer742;
    wxFlexGridSizer* flexGridSizer768;
    wxFlexGridSizer* flexGridSizer2404;
    wxStaticBitmap* m_toolStateTrafficLight;
    wxFlexGridSizer* flexGridSizerOutPanel;
    wxStaticText* m_staticText16032;
    wxComboBox* m_cbCurveLibResolution;
    wxBitmapToggleButton* m_switchCoordType;
    wxBitmapToggleButton* m_switchMonitoing;
    wxBitmapToggleButton* m_gridDrawPane;
    wxButton* m_traceDrawPane;
    wxButton* m_clearDrawPane;
    wxStaticText* m_staticText1054;
    wxComboBox* m_cbUpdateInterval;
    wxScrolledWindow* m_drawPaneWindow;
    wxFlexGridSizer* flexGridSizer885;
    wxFlexGridSizer* flexGridSizer3175;
    wxPanel* m_panel3281;
    wxPanel* m_yAxisMarker;
    wxPanel* m_panel32812;
    wxFlexGridSizer* flexGridSizer1416;
    wxPanel* m_xAxisMarkerTop;
    wxPanel* m_drawPane;
    wxPanel* m_xAxisMarkerBottom;
    wxFlexGridSizer* flexGridSizer936;
    wxFlexGridSizer* flexGridSizer1948;
    wxStaticText* m_staticText1950;
    wxComboBox* m_gridPosUnit;
    wxFlexGridSizer* flexGridSizer3167;
    wxStaticText* m_staticText3169;
    wxComboBox* m_cbDrawPaneZoom;
    wxFlexGridSizer* flexGridSizer1909;
    wxStaticText* m_staticText1943;
    wxTextCtrl* m_drawPainPositionX;
    wxStaticText* m_staticText19431;
    wxTextCtrl* m_drawPainPositionY;
    wxFlexGridSizer* flexGridSizer2803;
    wxStaticText* m_staticText1128;
    wxTextCtrl* m_crossings;
    wxStaticText* m_staticText1966;
    wxTextCtrl* m_passingCount;
    wxFlexGridSizer* flexGridSizer1698;
    wxStaticText* m_staticText1696;
    wxStaticText* m_minPosX;
    wxStaticText* m_minPosY;
    wxStaticText* m_minPosZ;
    wxStaticText* m_staticText1694;
    wxStaticText* m_maxPosX;
    wxStaticText* m_maxPosY;
    wxStaticText* m_maxPosZ;
    wxPanel* m_3DPane;
    wxFlexGridSizer* flexGridSizer2309;
    wxFlexGridSizer* flexGridSizer2311;
    wxButton* m_3D_Animate;
    wxButton* m_3D_Refreh;
    wxButton* m_3D_Clear;
    wxStaticLine* m_staticLine2348;
    wxButton* m_3D_Top;
    wxButton* m_3D_Bottom;
    wxButton* m_3D_Front;
    wxButton* m_3D_Rear;
    wxButton* m_3D_Left;
    wxButton* m_3D_Right4;
    wxButton* m_3D_Perspective;
    wxStaticLine* m_staticLine2341;
    wxButton* m_button2345;
    wxStaticLine* m_staticLine2343;
    wxStaticText* m_staticText2329;
    wxStaticText* m_staticText2331;
    wxStaticText* m_staticText2333;
    wxPanel* m_panel2590;
    wxFlexGridSizer* flexGridSizer2360;
    wxPanel* m_drawPane3D;
    wxTextCtrl* m_trace3D;
    wxPanel* m_panel2696;
    wxFlexGridSizer* flexGridSizer267117;
    wxFlexGridSizer* flexGridSizer3131;
    wxStaticText* m_staticText3133;
    wxCheckBox* m_cb3DDrawZeroPlane;
    wxCheckBox* m_cb3DDrawWorkpieceSurfacePlane;
    wxCheckBox* m_cb3DDrawWorkpieceOffset;
    wxStaticLine* m_staticLine3129;
    wxComboBox* m_planeSelect3D;
    wxStaticText* m_staticText268320;
    wxSpinCtrl* m_spin3DAngelX;
    wxStaticText* m_staticText268522;
    wxSpinCtrl* m_spin3DAngelY;
    wxStaticText* m_staticText268118;
    wxSpinCtrl* m_spin3DAngelZ;
    wxButton* m_button2710;
    wxPanel* m_svgEmuResult;
    wxFlexGridSizer* flexGridSizer585;
    wxFlexGridSizer* flexGridSizer766;
    wxButton* m_svgEmuOpenFileAsSource;
    wxButton* m_svgEmuOpenFileAsSvg;
    wxButton* m_svgEmuReload;
    wxButton* m_svgEmuClear;
    wxBitmapToggleButton* m_switchCoordTypeSvgOut;
    wxButton* m_svgEmuToggleOrigPath;
    wxButton* m_svgEmuZoomHome;
    wxButton* m_svgEmuZoomMinus;
    wxButton* m_svgEmuZoomPlus;
#if wxUSE_WEBVIEW
    wxWebView* m_svgView;
#endif // wxUSE_WEBVIEW

    wxPanel* m_svgEmuSource;
    wxFlexGridSizer* flexGridSizer1891;
    wxFlexGridSizer* flexGridSizer1899;
    wxBitmapToggleButton* m_svgEmuToggleWordWrap;
    wxStyledTextCtrl* m_stcEmuSource;
    wxPanel* m_svgTracePreview;
    wxFlexGridSizer* flexGridSizer1720;
    wxFlexGridSizer* flexGridSizer1858;
    wxBitmapButton* m_openXmlTraceAsText;
    wxBitmapButton* m_openXmlTrace;
    wxBitmapButton* m_copySvgTrace;
    wxFlexGridSizer* flexGridSizer1723;
#if wxUSE_WEBVIEW
    wxWebView* m_svgTrace;
#endif // wxUSE_WEBVIEW

    wxScrolledWindow* m_scrollSpy;
    wxFlexGridSizer* flexGridSizer27261;
    wxFlexGridSizer* flexGridSizer27302;
    wxButton* m_enableSerialSpy;
    wxButton* m_MarkSerialSpy;
    wxButton* m_clearSerialSpy;
    wxCheckBox* m_clearSerialSpyOnConnect;
    wxFlexGridSizer* flexGridSizer27417;
    wxTextCtrl* m_serialSpy;
    wxStaticText* m_staticText27519;
    wxTextCtrl* m_serialSpyDetails;
    wxPanel* m_svgUnitCalulator;
    wxFlexGridSizer* flexGridSizer3251;
    wxStaticText* m_staticText3261;
    wxComboBox* m_cbUCUnitFrom;
    wxStaticText* m_staticText3259;
    wxComboBox* m_cbUCUnitTo;
    wxFlexGridSizer* flexGridSizer3266;
    wxTextCtrl* m_cbUCValueFrom;
    wxTextCtrl* m_cbUCValueTo;
    wxButton* m_btUCClose;
    wxMenuBar* m_menuBar;
    wxMenu* m_menuFile;
    wxMenuItem* m_miNewTemplate;
    wxMenuItem* m_miOpenTemplate;
    wxMenuItem* m_miReloadTemplate;
    wxMenuItem* m_miSaveTemplate;
    wxMenuItem* m_miSaveTemplateAs;
    wxMenuItem* m_miSaveEmuOutput;
    wxMenuItem* m_sep20;
    wxMenuItem* m_miReinit;
    wxMenuItem* m_sep201;
    wxMenuItem* m_miExit;
    wxMenu* m_menuView;
    wxMenuItem* m_miPerspectiveDefault;
    wxMenuItem* m_miPerspectiveRun;
    wxMenuItem* m_miPerspectiveTemplate;
    wxMenuItem* m_menuItem2771;
    wxMenuItem* m_miToolbar;
    wxMenuItem* m_miViewMainView;
    wxMenuItem* m_miViewTemplateManager;
    wxMenuItem* m_miViewLogger;
    wxMenuItem* m_miViewMonitor;
    wxMenuItem* m_miViewSpy;
    wxMenuItem* m_miViewSpeed;
    wxMenuItem* m_miViewUnitCalculator;
    wxMenuItem* m_menuItem1665;
    wxMenuItem* m_miViewAll;
    wxMenuItem* m_miHideAll;
    wxMenu* m_menuMonitoring;
    wxMenuItem* m_menuItemUpdCoors;
    wxMenuItem* m_menuItemUpdDraw;
    wxMenuItem* m_menuItemAllowEvents;
    wxMenuItem* m_menuItemDisplayUserAgent;
    wxMenuItem* m_menuItemToolControls;
    wxMenuItem* m_menuSeparator726;
    wxMenuItem* m_menuItemDebugSerial;
    wxMenuItem* m_menuItemFreezeLogger;
    wxMenuItem* m_menuSeparator1725;
    wxMenuItem* m_menuItemMinMonitoring;
    wxMenuItem* m_menuItemNormalMonitoring;
    wxMenu* m_menuRequestor;
    wxMenuItem* m_miRqtIdleMessages;
    wxMenuItem* m_menuItem2530;
    wxMenuItem* m_miRqtVersion;
    wxMenuItem* m_miRqtConfig;
    wxMenuItem* m_miRqtPins;
    wxMenuItem* m_menuErrorCount;
    wxMenuItem* m_miRqtErrorInfo;
    wxMenuItem* m_menuItem1187;
    wxMenuItem* m_miMotorEnableState;
    wxMenuItem* m_menuItem881;
    wxMenuItem* m_miRqtCurPos;
    wxMenuItem* m_miRqtLimit;
    wxMenuItem* m_menuItem1183;
    wxMenuItem* m_miReset;
    wxMenu* m_menuTools;
    wxMenuItem* m_miManuallyDissolveEndState;
    wxMenuItem* m_sep1559;
    wxMenuItem* m_miPathGenerator;
    wxMenuItem* m_miIniFile;
    wxMenuItem* m_miExternalEditor;
    wxMenuItem* m_miCalculator;
    wxMenuItem* m_miPyCam;
    wxMenu* m_menuTest;
    wxMenuItem* m_miTest1;
    wxMenuItem* m_miTest2;
    wxMenuItem* m_miTest3;
    wxMenuItem* m_miTest4;
    wxMenu* m_menuAbout;
    wxMenuItem* m_menuItem309;
    wxTimer* m_startupTimer;
    wxTimer* m_serialTimer;
    wxTimer* m_traceTimer;

protected:
    virtual void activateMainWindow(wxActivateEvent& event) { event.Skip(); }
    virtual void closeAuiPane(wxAuiManagerEvent& event) { event.Skip(); }
    virtual void maximizeAuiPane(wxAuiManagerEvent& event) { event.Skip(); }
    virtual void restoreAuiPane(wxAuiManagerEvent& event) { event.Skip(); }
    virtual void renderAuiPane(wxAuiManagerEvent& event) { event.Skip(); }
    virtual void selectPort(wxCommandEvent& event) { event.Skip(); }
    virtual void connect(wxCommandEvent& event) { event.Skip(); }
    virtual void selectUnit(wxCommandEvent& event) { event.Skip(); }
    virtual void cfgStepDelayDropDown(wxAuiToolBarEvent& event) { event.Skip(); }
    virtual void cfgStepDelayMin(wxCommandEvent& event) { event.Skip(); }
    virtual void cfgStepDelayMax(wxCommandEvent& event) { event.Skip(); }
    virtual void cfgStepDelayArduino(wxCommandEvent& event) { event.Skip(); }
    virtual void stepDelayChanged(wxScrollEvent& event) { event.Skip(); }
    virtual void stepDelayThumbtrack(wxScrollEvent& event) { event.Skip(); }
    virtual void rcReset(wxCommandEvent& event) { event.Skip(); }
    virtual void rcSelectRunMode(wxCommandEvent& event) { event.Skip(); }
    virtual void rcRun(wxCommandEvent& event) { event.Skip(); }
    virtual void rcPause(wxCommandEvent& event) { event.Skip(); }
    virtual void rcNextPath(wxCommandEvent& event) { event.Skip(); }
    virtual void rcNextStep(wxCommandEvent& event) { event.Skip(); }
    virtual void rcFinish(wxCommandEvent& event) { event.Skip(); }
    virtual void rcStop(wxCommandEvent& event) { event.Skip(); }
    virtual void controlerPause(wxCommandEvent& event) { event.Skip(); }
    virtual void emergencyStop(wxCommandEvent& event) { event.Skip(); }
    virtual void mainBookPageChanged(wxNotebookEvent& event) { event.Skip(); }
    virtual void mainBookPageChanging(wxNotebookEvent& event) { event.Skip(); }
    virtual void mvSpinUpX(wxSpinEvent& event) { event.Skip(); }
    virtual void mvSpinDownX(wxSpinEvent& event) { event.Skip(); }
    virtual void mvSpinDownY(wxSpinEvent& event) { event.Skip(); }
    virtual void mvSpinUpY(wxSpinEvent& event) { event.Skip(); }
    virtual void keyDownXY(wxKeyEvent& event) { event.Skip(); }
    virtual void setFocusMoveXYAxis(wxFocusEvent& event) { event.Skip(); }
    virtual void killFocusMoveXYAxis(wxFocusEvent& event) { event.Skip(); }
    virtual void mvSpinUpZ(wxSpinEvent& event) { event.Skip(); }
    virtual void mvSpinDownZ(wxSpinEvent& event) { event.Skip(); }
    virtual void keyDownZ(wxKeyEvent& event) { event.Skip(); }
    virtual void setFocusMoveZAxis(wxFocusEvent& event) { event.Skip(); }
    virtual void killFocusMoveZAxis(wxFocusEvent& event) { event.Skip(); }
    virtual void updateInclWpt(wxCommandEvent& event) { event.Skip(); }
    virtual void setZero(wxCommandEvent& event) { event.Skip(); }
    virtual void moveHome(wxCommandEvent& event) { event.Skip(); }
    virtual void moveToZeroXY(wxCommandEvent& event) { event.Skip(); }
    virtual void moveToZeroXYZ(wxCommandEvent& event) { event.Skip(); }
    virtual void moveToZeroZ(wxCommandEvent& event) { event.Skip(); }
    virtual void moveXToMax(wxCommandEvent& event) { event.Skip(); }
    virtual void moveXToMid(wxCommandEvent& event) { event.Skip(); }
    virtual void moveXToMin(wxCommandEvent& event) { event.Skip(); }
    virtual void moveYToMax(wxCommandEvent& event) { event.Skip(); }
    virtual void moveYToMid(wxCommandEvent& event) { event.Skip(); }
    virtual void moveYToMin(wxCommandEvent& event) { event.Skip(); }
    virtual void moveZToMax(wxCommandEvent& event) { event.Skip(); }
    virtual void moveZToMid(wxCommandEvent& event) { event.Skip(); }
    virtual void moveZToMin(wxCommandEvent& event) { event.Skip(); }
    virtual void moveZToTop(wxCommandEvent& event) { event.Skip(); }
    virtual void moveZToBottom(wxCommandEvent& event) { event.Skip(); }
    virtual void killFocusWorkpieceThickness(wxFocusEvent& event) { event.Skip(); }
    virtual void killFocusCrossingThickness(wxFocusEvent& event) { event.Skip(); }
    virtual void killFocusRouterDiameter(wxFocusEvent& event) { event.Skip(); }
    virtual void killFocusReplyThreshold(wxFocusEvent& event) { event.Skip(); }
    virtual void updateReverseStepSignX(wxCommandEvent& event) { event.Skip(); }
    virtual void updateReverseStepSignY(wxCommandEvent& event) { event.Skip(); }
    virtual void selectPreconfiguredSpeedSetups(wxCommandEvent& event) { event.Skip(); }
    virtual void killFocusMaxSpeedXY(wxFocusEvent& event) { event.Skip(); }
    virtual void updateFlySpeedXY(wxCommandEvent& event) { event.Skip(); }
    virtual void updateWorkSpeedXY(wxCommandEvent& event) { event.Skip(); }
    virtual void updateCurrentSpeedXY(wxCommandEvent& event) { event.Skip(); }
    virtual void configureXYSpeedWithZValues(wxCommandEvent& event) { event.Skip(); }
    virtual void killFocusMaxSpeedZ(wxFocusEvent& event) { event.Skip(); }
    virtual void updateFlySpeedZ(wxCommandEvent& event) { event.Skip(); }
    virtual void updateWorkSpeedZ(wxCommandEvent& event) { event.Skip(); }
    virtual void updateCurrentSpeedZ(wxCommandEvent& event) { event.Skip(); }
    virtual void configureZSpeedWithXYValues(wxCommandEvent& event) { event.Skip(); }
    virtual void killFocusMaxDimensionX(wxFocusEvent& event) { event.Skip(); }
    virtual void killFocusMaxDimensionY(wxFocusEvent& event) { event.Skip(); }
    virtual void killFocusMaxDimensionZ(wxFocusEvent& event) { event.Skip(); }
    virtual void treebookTestChanged(wxTreebookEvent& event) { event.Skip(); }
    virtual void selectTestIntervalMode(wxCommandEvent& event) { event.Skip(); }
    virtual void testCountXSpinCtl(wxSpinEvent& event) { event.Skip(); }
    virtual void testCountXUpdated(wxCommandEvent& event) { event.Skip(); }
    virtual void testDimTakeOverX(wxCommandEvent& event) { event.Skip(); }
    virtual void testDimTakeOverY(wxCommandEvent& event) { event.Skip(); }
    virtual void testDimTakeOverZ(wxCommandEvent& event) { event.Skip(); }
    virtual void testDimTakeOverAll(wxCommandEvent& event) { event.Skip(); }
    virtual void testEndSwitchEvaluation(wxCommandEvent& event) { event.Skip(); }
    virtual void testSwitchToolOnOff(wxCommandEvent& event) { event.Skip(); }
    virtual void ctrlTestCaseSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void checkManuallyXY(wxCommandEvent& event) { event.Skip(); }
    virtual void minManuallyXSlider(wxCommandEvent& event) { event.Skip(); }
    virtual void updateMetricX(wxCommandEvent& event) { event.Skip(); }
    virtual void maxManuallyXSlider(wxCommandEvent& event) { event.Skip(); }
    virtual void zeroManuallyXSlider(wxCommandEvent& event) { event.Skip(); }
    virtual void signManuallyXSlider(wxCommandEvent& event) { event.Skip(); }
    virtual void moveManuallySliderX(wxScrollEvent& event) { event.Skip(); }
    virtual void changeManuallySliderX(wxScrollEvent& event) { event.Skip(); }
    virtual void minManuallyYSlider(wxCommandEvent& event) { event.Skip(); }
    virtual void updateMetricY(wxCommandEvent& event) { event.Skip(); }
    virtual void maxManuallyYSlider(wxCommandEvent& event) { event.Skip(); }
    virtual void zeroManuallyYSlider(wxCommandEvent& event) { event.Skip(); }
    virtual void signManuallyYSlider(wxCommandEvent& event) { event.Skip(); }
    virtual void moveManuallySliderY(wxScrollEvent& event) { event.Skip(); }
    virtual void changeManuallySliderY(wxScrollEvent& event) { event.Skip(); }
    virtual void checkManuallyZ(wxCommandEvent& event) { event.Skip(); }
    virtual void minManuallyZSlider(wxCommandEvent& event) { event.Skip(); }
    virtual void updateMetricZ(wxCommandEvent& event) { event.Skip(); }
    virtual void maxManuallyZSlider(wxCommandEvent& event) { event.Skip(); }
    virtual void zeroManuallyZSlider(wxCommandEvent& event) { event.Skip(); }
    virtual void signManuallyZSlider(wxCommandEvent& event) { event.Skip(); }
    virtual void moveManuallySliderZ(wxScrollEvent& event) { event.Skip(); }
    virtual void changeManuallySliderZ(wxScrollEvent& event) { event.Skip(); }
    virtual void openTemplateSourceExtern(wxCommandEvent& event) { event.Skip(); }
    virtual void openTemplateSvgExtern(wxCommandEvent& event) { event.Skip(); }
    virtual void openSVGPathGenerator(wxCommandEvent& event) { event.Skip(); }
    virtual void saveTemplateFromButton(wxCommandEvent& event) { event.Skip(); }
    virtual void reloadTemplateFromButton(wxCommandEvent& event) { event.Skip(); }
    virtual void toggleTemplateWordWrapMode(wxCommandEvent& event) { event.Skip(); }
    virtual void togglePreviewErrorInfo(wxCommandEvent& event) { event.Skip(); }
    virtual void fileContentKeyDown(wxKeyEvent& event) { event.Skip(); }
    virtual void fileContentLeftDown(wxMouseEvent& event) { event.Skip(); }
    virtual void fileContentLeftUp(wxMouseEvent& event) { event.Skip(); }
    virtual void fileContentRightDown(wxMouseEvent& event) { event.Skip(); }
    virtual void marginClickFileContent(wxStyledTextEvent& event) { event.Skip(); }
    virtual void fileContentKeyUp(wxKeyEvent& event) { event.Skip(); }
    virtual void fileContentChange(wxStyledTextEvent& event) { event.Skip(); }
    virtual void fileContentDClick(wxMouseEvent& event) { event.Skip(); }
    virtual void toogleSvgEditSearchFlag(wxCommandEvent& event) { event.Skip(); }
    virtual void svgEditSearchTextChanged(wxCommandEvent& event) { event.Skip(); }
    virtual void svgEditSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void svgEditFind(wxCommandEvent& event) { event.Skip(); }
    virtual void svgEditFindPrev(wxCommandEvent& event) { event.Skip(); }
    virtual void selectUAInboundPathList(wxDataViewEvent& event) { event.Skip(); }
    virtual void selectUAUseDirectiveList(wxDataViewEvent& event) { event.Skip(); }
    virtual void selectUADetailInfo(wxDataViewEvent& event) { event.Skip(); }
    virtual void selectSvgDebuggerInfoBase(wxDataViewEvent& event) { event.Skip(); }
    virtual void selectSvgDebuggerInfoPath(wxDataViewEvent& event) { event.Skip(); }
    virtual void selectSvgDebuggerInfoDetail(wxDataViewEvent& event) { event.Skip(); }
    #if wxUSE_WEBVIEW
    #endif // wxUSE_WEBVIEW
    virtual void leaveEnterFileManagerControl(wxMouseEvent& event) { event.Skip(); }
    virtual void lruListItemActivated(wxCommandEvent& event) { event.Skip(); }
    virtual void lruListItemSelected(wxCommandEvent& event) { event.Skip(); }
    virtual void leaveLruList(wxMouseEvent& event) { event.Skip(); }
    virtual void selectDefaultDirectory(wxCommandEvent& event) { event.Skip(); }
    virtual void selectCurrentFile(wxCommandEvent& event) { event.Skip(); }
    virtual void dirCtrlChanged(wxTreeEvent& event) { event.Skip(); }
    virtual void dirCtrlActivated(wxTreeEvent& event) { event.Skip(); }
    virtual void clearLogger(wxCommandEvent& event) { event.Skip(); }
    virtual void freezeLogger(wxCommandEvent& event) { event.Skip(); }
    virtual void copyLogger(wxCommandEvent& event) { event.Skip(); }
    virtual void UpdateLogger(wxCommandEvent& event) { event.Skip(); }
    virtual void traceTextUpdated(wxCommandEvent& event) { event.Skip(); }
    virtual void dclickDurationCount(wxMouseEvent& event) { event.Skip(); }
    virtual void requestCurrentLimitStateIcon(wxMouseEvent& event) { event.Skip(); }
    virtual void outboundBookChanged(wxNotebookEvent& event) { event.Skip(); }
    virtual void outboundBookChanging(wxNotebookEvent& event) { event.Skip(); }
    virtual void nootebookConfigChanged(wxListbookEvent& event) { event.Skip(); }
    virtual void cancelRun(wxCommandEvent& event) { event.Skip(); }
    virtual void confirmRun(wxCommandEvent& event) { event.Skip(); }
    virtual void clearProcessedSetterList(wxCommandEvent& event) { event.Skip(); }
    virtual void requestControllerConfigFromButton(wxCommandEvent& event) { event.Skip(); }
    virtual void requestControllerPinsFromButton(wxCommandEvent& event) { event.Skip(); }
    virtual void clearControllerMsgHistory(wxCommandEvent& event) { event.Skip(); }
    virtual void requestControllerErrorInfoFromButton(wxCommandEvent& event) { event.Skip(); }
    virtual void updateCurveLibResolution(wxCommandEvent& event) { event.Skip(); }
    virtual void switchCoordinateSystemType(wxCommandEvent& event) { event.Skip(); }
    virtual void switchMonitoring(wxCommandEvent& event) { event.Skip(); }
    virtual void gridDrawPane(wxCommandEvent& event) { event.Skip(); }
    virtual void traceDrawPane(wxCommandEvent& event) { event.Skip(); }
    virtual void clearDrawPane(wxCommandEvent& event) { event.Skip(); }
    virtual void changeUpdateInterval(wxCommandEvent& event) { event.Skip(); }
    virtual void paintDrawPaneWindow(wxPaintEvent& event) { event.Skip(); }
    virtual void paintYAxisMarker(wxPaintEvent& event) { event.Skip(); }
    virtual void paintXAxisMarkerTop(wxPaintEvent& event) { event.Skip(); }
    virtual void onPaintDrawPane(wxPaintEvent& event) { event.Skip(); }
    virtual void onMotionDrawPane(wxMouseEvent& event) { event.Skip(); }
    virtual void onLeaveDrawPane(wxMouseEvent& event) { event.Skip(); }
    virtual void onKeyDownDrawPane(wxKeyEvent& event) { event.Skip(); }
    virtual void onMouseWheelDrawPane(wxMouseEvent& event) { event.Skip(); }
    virtual void paintXAxisMarkerBottom(wxPaintEvent& event) { event.Skip(); }
    virtual void selectGridPosUnit(wxCommandEvent& event) { event.Skip(); }
    virtual void changeDrawPaneZoom(wxCommandEvent& event) { event.Skip(); }
    virtual void animate3D(wxCommandEvent& event) { event.Skip(); }
    virtual void refresh3D(wxCommandEvent& event) { event.Skip(); }
    virtual void clear3D(wxCommandEvent& event) { event.Skip(); }
    virtual void showFromTop3D(wxCommandEvent& event) { event.Skip(); }
    virtual void showFromBottom3D(wxCommandEvent& event) { event.Skip(); }
    virtual void showFromFront3D(wxCommandEvent& event) { event.Skip(); }
    virtual void showFromRear3D(wxCommandEvent& event) { event.Skip(); }
    virtual void showFromLeft3D(wxCommandEvent& event) { event.Skip(); }
    virtual void showFromRight3D(wxCommandEvent& event) { event.Skip(); }
    virtual void show3D(wxCommandEvent& event) { event.Skip(); }
    virtual void runOpenGLTest(wxCommandEvent& event) { event.Skip(); }
    virtual void update3DDrawOptions(wxCommandEvent& event) { event.Skip(); }
    virtual void selectedPlane3D(wxCommandEvent& event) { event.Skip(); }
    virtual void spin3DAngelX(wxSpinEvent& event) { event.Skip(); }
    virtual void update3DAngelX(wxCommandEvent& event) { event.Skip(); }
    virtual void spin3DAngelY(wxSpinEvent& event) { event.Skip(); }
    virtual void update3DAngelY(wxCommandEvent& event) { event.Skip(); }
    virtual void spin3DAngelZ(wxSpinEvent& event) { event.Skip(); }
    virtual void update3DAngelZ(wxCommandEvent& event) { event.Skip(); }
    virtual void show3DPaneHelp(wxCommandEvent& event) { event.Skip(); }
    virtual void svgEmuOpenFileAsSource(wxCommandEvent& event) { event.Skip(); }
    virtual void svgEmuOpenFileAsSvg(wxCommandEvent& event) { event.Skip(); }
    virtual void svgEmuReload(wxCommandEvent& event) { event.Skip(); }
    virtual void svgEmuClear(wxCommandEvent& event) { event.Skip(); }
    virtual void switchCoordinateSystemTypeSvgOut(wxCommandEvent& event) { event.Skip(); }
    virtual void svgEmuToogleOriginalPath(wxCommandEvent& event) { event.Skip(); }
    virtual void svgEmuZoomHome(wxCommandEvent& event) { event.Skip(); }
    virtual void svgEmuZoomMinus(wxCommandEvent& event) { event.Skip(); }
    virtual void svgEmuZoomPlus(wxCommandEvent& event) { event.Skip(); }
    virtual void toggleEmuWordWrapMode(wxCommandEvent& event) { event.Skip(); }
    virtual void emuContentRightDown(wxMouseEvent& event) { event.Skip(); }
    virtual void marginClickEmuSource(wxStyledTextEvent& event) { event.Skip(); }
    virtual void emuContentDClick(wxMouseEvent& event) { event.Skip(); }
    virtual void openXMLTraceAsText(wxCommandEvent& event) { event.Skip(); }
    virtual void OpenXmlTrace(wxCommandEvent& event) { event.Skip(); }
    virtual void copySvgTrace(wxCommandEvent& event) { event.Skip(); }
    virtual void enableSerialSpy(wxCommandEvent& event) { event.Skip(); }
    virtual void markSerialSpy(wxCommandEvent& event) { event.Skip(); }
    virtual void clearSerialSpy(wxCommandEvent& event) { event.Skip(); }
    virtual void selectUCUnitFrom(wxCommandEvent& event) { event.Skip(); }
    virtual void selectUCUnitTo(wxCommandEvent& event) { event.Skip(); }
    virtual void selectUCChangeFrom(wxCommandEvent& event) { event.Skip(); }
    virtual void closeUnitCalculator(wxCommandEvent& event) { event.Skip(); }
    virtual void newTemplate(wxCommandEvent& event) { event.Skip(); }
    virtual void openTemplate(wxCommandEvent& event) { event.Skip(); }
    virtual void reloadTemplate(wxCommandEvent& event) { event.Skip(); }
    virtual void saveTemplate(wxCommandEvent& event) { event.Skip(); }
    virtual void saveTemplateAs(wxCommandEvent& event) { event.Skip(); }
    virtual void saveEmuOutput(wxCommandEvent& event) { event.Skip(); }
    virtual void reinit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }
    virtual void perspectiveDefault(wxCommandEvent& event) { event.Skip(); }
    virtual void perspectiveRun(wxCommandEvent& event) { event.Skip(); }
    virtual void perspectiveTemplate(wxCommandEvent& event) { event.Skip(); }
    virtual void viewToolbar(wxCommandEvent& event) { event.Skip(); }
    virtual void viewMainView(wxCommandEvent& event) { event.Skip(); }
    virtual void viewTemplateManager(wxCommandEvent& event) { event.Skip(); }
    virtual void viewLogger(wxCommandEvent& event) { event.Skip(); }
    virtual void viewMonitor(wxCommandEvent& event) { event.Skip(); }
    virtual void viewSpy(wxCommandEvent& event) { event.Skip(); }
    virtual void viewSpeed(wxCommandEvent& event) { event.Skip(); }
    virtual void viewUnitCalculator(wxCommandEvent& event) { event.Skip(); }
    virtual void viewAllAuiPanes(wxCommandEvent& event) { event.Skip(); }
    virtual void hideAllAuiPanes(wxCommandEvent& event) { event.Skip(); }
    virtual void defineUpdateCoordinates(wxCommandEvent& event) { event.Skip(); }
    virtual void defineOnlineDrawing(wxCommandEvent& event) { event.Skip(); }
    virtual void defineAllowEvents(wxCommandEvent& event) { event.Skip(); }
    virtual void displayUserAgent(wxCommandEvent& event) { event.Skip(); }
    virtual void updateToolControls(wxCommandEvent& event) { event.Skip(); }
    virtual void defineDebugSerial(wxCommandEvent& event) { event.Skip(); }
    virtual void defineMinMonitoring(wxCommandEvent& event) { event.Skip(); }
    virtual void defineNormalMonitoring(wxCommandEvent& event) { event.Skip(); }
    virtual void requestVersion(wxCommandEvent& event) { event.Skip(); }
    virtual void requestConfig(wxCommandEvent& event) { event.Skip(); }
    virtual void requestPins(wxCommandEvent& event) { event.Skip(); }
    virtual void requestErrorCount(wxCommandEvent& event) { event.Skip(); }
    virtual void requestErrorInfo(wxCommandEvent& event) { event.Skip(); }
    virtual void requestEnableStepperMotors(wxCommandEvent& event) { event.Skip(); }
    virtual void requestCurrentPos(wxCommandEvent& event) { event.Skip(); }
    virtual void requestCurrentLimitState(wxCommandEvent& event) { event.Skip(); }
    virtual void requestReset(wxCommandEvent& event) { event.Skip(); }
    virtual void dissolveEndSwitchStates(wxCommandEvent& event) { event.Skip(); }
    virtual void openConfigurationFile(wxCommandEvent& event) { event.Skip(); }
    virtual void openExternalEditor(wxCommandEvent& event) { event.Skip(); }
    virtual void openCalculator(wxCommandEvent& event) { event.Skip(); }
    virtual void openPyCam(wxCommandEvent& event) { event.Skip(); }
    virtual void testFunction1(wxCommandEvent& event) { event.Skip(); }
    virtual void testFunction2(wxCommandEvent& event) { event.Skip(); }
    virtual void testFunction3(wxCommandEvent& event) { event.Skip(); }
    virtual void testFunction4(wxCommandEvent& event) { event.Skip(); }
    virtual void OnAbout(wxCommandEvent& event) { event.Skip(); }
    virtual void startupTimer(wxTimerEvent& event) { event.Skip(); }
    virtual void serialTimer(wxTimerEvent& event) { event.Skip(); }
    virtual void traceTimer(wxTimerEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText1842() { return m_staticText1842; }
    wxComboBox* GetPortSelector() { return m_portSelector; }
    wxBitmapButton* GetConnect() { return m_connect; }
    wxStaticText* GetStaticText752() { return m_staticText752; }
    wxComboBox* GetUnit() { return m_unit; }
    wxStaticText* GetStaticText1748() { return m_staticText1748; }
    wxSlider* GetStepDelay() { return m_stepDelay; }
    wxStaticText* GetStepDelayValue() { return m_stepDelayValue; }
    wxBitmapButton* GetRcReset() { return m_rcReset; }
    wxBitmapButton* GetRcRun() { return m_rcRun; }
    wxBitmapButton* GetRcPause() { return m_rcPause; }
    wxBitmapButton* GetRcNextPath() { return m_rcNextPath; }
    wxBitmapButton* GetRcNextStep() { return m_rcNextStep; }
    wxBitmapButton* GetRcFinish() { return m_rcFinish; }
    wxBitmapButton* GetRcStop() { return m_rcStop; }
    wxBitmapButton* GetControlerPause() { return m_controlerPause; }
    wxButton* GetBtnEmergenyStop() { return m_btnEmergenyStop; }

    virtual void ShowAuiToolMenu(wxAuiToolBarEvent& event);
    wxAuiToolBar* GetAuibarMain() { return m_auibarMain; }
    wxStaticText* GetStaticText779() { return m_staticText779; }
    wxStaticLine* GetStaticLine783() { return m_staticLine783; }
    wxStaticText* GetStaticText821() { return m_staticText821; }
    wxSpinButton* GetSpinButtonX() { return m_spinButtonX; }
    wxStaticText* GetStaticText63169() { return m_staticText63169; }
    wxSpinButton* GetSpinButtonY() { return m_spinButtonY; }
    wxTextCtrl* GetMoveXYAxisCtl() { return m_moveXYAxisCtl; }
    wxStaticText* GetStaticText823() { return m_staticText823; }
    wxStaticText* GetStaticText6316() { return m_staticText6316; }
    wxStaticText* GetStaticText825() { return m_staticText825; }
    wxStaticText* GetStaticText827() { return m_staticText827; }
    wxStaticText* GetStaticText631() { return m_staticText631; }
    wxStaticText* GetStaticText832() { return m_staticText832; }
    wxStaticText* GetStaticText834() { return m_staticText834; }
    wxSpinButton* GetSpinButtonZ() { return m_spinButtonZ; }
    wxTextCtrl* GetMoveZAxisCtl() { return m_moveZAxisCtl; }
    wxStaticText* GetStaticText830() { return m_staticText830; }
    wxStaticText* GetStaticText836() { return m_staticText836; }
    wxCheckBox* GetIncludingWpt() { return m_includingWpt; }
    wxButton* GetSetZero() { return m_setZero; }
    wxStaticText* GetStaticText1156() { return m_staticText1156; }
    wxStaticLine* GetStaticLine1158() { return m_staticLine1158; }
    wxStaticText* GetStaticText1171() { return m_staticText1171; }
    wxStaticText* GetStaticText1173() { return m_staticText1173; }
    wxComboBox* GetHomeDefintion() { return m_homeDefintion; }
    wxButton* GetMoveHome() { return m_moveHome; }
    wxStaticLine* GetStaticLine2177() { return m_staticLine2177; }
    wxStaticLine* GetStaticLine2179() { return m_staticLine2179; }
    wxStaticText* GetStaticText2182() { return m_staticText2182; }
    wxComboBox* GetZeroMoveModeXY() { return m_zeroMoveModeXY; }
    wxButton* GetMoveXYtoZero() { return m_moveXYtoZero; }
    wxStaticText* GetStaticText218228() { return m_staticText218228; }
    wxComboBox* GetZeroMoveModeXYZ() { return m_zeroMoveModeXYZ; }
    wxButton* GetMoveXYZtoZero() { return m_moveXYZtoZero; }
    wxStaticText* GetStaticText21822831() { return m_staticText21822831; }
    wxComboBox* GetZeroMoveModeZ() { return m_zeroMoveModeZ; }
    wxButton* GetMoveZtoZero() { return m_moveZtoZero; }
    wxStaticLine* GetStaticLine2191() { return m_staticLine2191; }
    wxStaticLine* GetStaticLine2193() { return m_staticLine2193; }
    wxStaticText* GetStaticText1177233() { return m_staticText1177233; }
    wxStaticText* GetStaticText11772() { return m_staticText11772; }
    wxButton* GetXToMax() { return m_xToMax; }
    wxButton* GetXToMid() { return m_xToMid; }
    wxButton* GetXToMin() { return m_xToMin; }
    wxButton* GetYToMax() { return m_yToMax; }
    wxButton* GetYToMid() { return m_yToMid; }
    wxButton* GetYToMin() { return m_yToMin; }
    wxStaticLine* GetStaticLine2195() { return m_staticLine2195; }
    wxStaticLine* GetStaticLine2197() { return m_staticLine2197; }
    wxStaticText* GetStaticText1175() { return m_staticText1175; }
    wxStaticText* GetStaticText1177() { return m_staticText1177; }
    wxButton* GetZToMax() { return m_zToMax; }
    wxButton* GetZToMid() { return m_zToMid; }
    wxButton* GetZToMin() { return m_zToMin; }
    wxButton* GetZToTop() { return m_zToTop; }
    wxStaticText* GetStaticText2438() { return m_staticText2438; }
    wxButton* GetZToBottom() { return m_zToBottom; }
    wxPanel* GetPanelReference() { return m_panelReference; }
    wxStaticText* GetStaticText7791() { return m_staticText7791; }
    wxStaticLine* GetStaticLine9572() { return m_staticLine9572; }
    wxStaticText* GetStaticText569() { return m_staticText569; }
    wxTextCtrl* GetWorkpieceThickness() { return m_workpieceThickness; }
    wxStaticText* GetStaticText1289() { return m_staticText1289; }
    wxTextCtrl* GetCrossingThickness() { return m_crossingThickness; }
    wxStaticLine* GetStaticLine3109() { return m_staticLine3109; }
    wxStaticText* GetStaticText57510() { return m_staticText57510; }
    wxComboBox* GetCbToolType() { return m_cbToolType; }
    wxStaticText* GetStaticText575() { return m_staticText575; }
    wxTextCtrl* GetRouterBitDiameter() { return m_routerBitDiameter; }
    wxStaticLine* GetStaticLine3111() { return m_staticLine3111; }
    wxStaticText* GetStaticText12374() { return m_staticText12374; }
    wxTextCtrl* GetReplyThreshold() { return m_replyThreshold; }
    wxStaticText* GetStaticText1517() { return m_staticText1517; }
    wxComboBox* GetCbStepSignX() { return m_cbStepSignX; }
    wxStaticText* GetStaticText1519() { return m_staticText1519; }
    wxComboBox* GetCbStepSignY() { return m_cbStepSignY; }
    wxStaticText* GetStaticText1479() { return m_staticText1479; }
    wxComboBox* GetCbUseProceesdSetterList() { return m_cbUseProceesdSetterList; }
    wxStaticText* GetStaticText1475() { return m_staticText1475; }
    wxComboBox* GetCbClearProceesdSetterList() { return m_cbClearProceesdSetterList; }
    wxPanel* GetSetupWorkPage() { return m_setupWorkPage; }
    wxStaticText* GetStaticText779125() { return m_staticText779125; }
    wxStaticLine* GetStaticLine957236() { return m_staticLine957236; }
    wxStaticText* GetStaticText2798() { return m_staticText2798; }
    wxComboBox* GetCbPreconfiguredSpeedSetups() { return m_cbPreconfiguredSpeedSetups; }
    wxStaticLine* GetStaticLine9572361() { return m_staticLine9572361; }
    wxStaticText* GetStaticText9241() { return m_staticText9241; }
    wxTextCtrl* GetMaxXYSpeed() { return m_maxXYSpeed; }
    wxStaticText* GetStaticText924() { return m_staticText924; }
    wxComboBox* GetFlySpeedXY() { return m_flySpeedXY; }
    wxStaticText* GetStaticText932() { return m_staticText932; }
    wxComboBox* GetWorkSpeedXY() { return m_workSpeedXY; }
    wxStaticText* GetStaticText1019() { return m_staticText1019; }
    wxComboBox* GetCurrentSpeedXY() { return m_currentSpeedXY; }
    wxButton* GetButton266116() { return m_button266116; }
    wxStaticLine* GetStaticLine3113() { return m_staticLine3113; }
    wxStaticText* GetStaticText1208() { return m_staticText1208; }
    wxTextCtrl* GetMaxZSpeed() { return m_maxZSpeed; }
    wxStaticText* GetStaticText92813() { return m_staticText92813; }
    wxComboBox* GetFlySpeedZ() { return m_flySpeedZ; }
    wxStaticText* GetStaticText1213() { return m_staticText1213; }
    wxComboBox* GetWorkSpeedZ() { return m_workSpeedZ; }
    wxStaticText* GetStaticText101911() { return m_staticText101911; }
    wxComboBox* GetCurrentSpeedZ() { return m_currentSpeedZ; }
    wxButton* GetButton2661() { return m_button2661; }
    wxPanel* GetSetupSpeedPage() { return m_setupSpeedPage; }
    wxStaticText* GetStaticText77912() { return m_staticText77912; }
    wxStaticLine* GetStaticLine95723() { return m_staticLine95723; }
    wxStaticText* GetStaticText854() { return m_staticText854; }
    wxTextCtrl* GetMaxXDimension() { return m_maxXDimension; }
    wxStaticText* GetStaticText856() { return m_staticText856; }
    wxTextCtrl* GetMaxYDimension() { return m_maxYDimension; }
    wxStaticText* GetStaticText85611() { return m_staticText85611; }
    wxTextCtrl* GetMaxZDimension() { return m_maxZDimension; }
    wxPanel* GetSetupDimPage() { return m_setupDimPage; }
    wxStaticText* GetStaticText77914() { return m_staticText77914; }
    wxStaticLine* GetStaticLine95725() { return m_staticLine95725; }
    wxStaticText* GetStaticText1237() { return m_staticText1237; }
    wxComboBox* GetCbSvgZoom() { return m_cbSvgZoom; }
    wxStaticText* GetStaticText1261() { return m_staticText1261; }
    wxComboBox* GetCbSvgIncludeOriginalPath() { return m_cbSvgIncludeOriginalPath; }
    wxStaticText* GetStaticText126111() { return m_staticText126111; }
    wxComboBox* GetCbSvgFirstCrossing() { return m_cbSvgFirstCrossing; }
    wxPanel* GetSetupSVGPage() { return m_setupSVGPage; }
    wxStaticText* GetStaticText1880() { return m_staticText1880; }
    wxStaticLine* GetStaticLine2226() { return m_staticLine2226; }
    wxTextCtrl* GetEnvrionmentInfo() { return m_envrionmentInfo; }
    wxPanel* GetSetupEnvPage() { return m_setupEnvPage; }
    wxStaticText* GetStaticText779122() { return m_staticText779122; }
    wxStaticLine* GetStaticLine957233() { return m_staticLine957233; }
    wxStaticText* GetStaticText123753() { return m_staticText123753; }
    wxComboBox* GetCbRunMotionMonitorMode() { return m_cbRunMotionMonitorMode; }
    wxStaticText* GetStaticText12375() { return m_staticText12375; }
    wxComboBox* GetCbRunConfirmationMode() { return m_cbRunConfirmationMode; }
    wxPanel* GetSetupApp() { return m_setupApp; }
    wxListbook* GetListbook2220() { return m_listbook2220; }
    wxPanel* GetPanelSetup() { return m_panelSetup; }
    wxStaticText* GetStaticText2117() { return m_staticText2117; }
    wxStaticLine* GetStaticLine2253() { return m_staticLine2253; }
    wxComboBox* GetTestIntervalMode() { return m_testIntervalMode; }
    wxStaticText* GetStaticText2105() { return m_staticText2105; }
    wxStaticText* GetStaticText2107() { return m_staticText2107; }
    wxStaticText* GetStaticText2109() { return m_staticText2109; }
    wxStaticText* GetStaticText2149() { return m_staticText2149; }
    wxStaticText* GetStaticText2115() { return m_staticText2115; }
    wxStaticText* GetStaticText2165() { return m_staticText2165; }
    wxStaticLine* GetStaticLine2111() { return m_staticLine2111; }
    wxStaticText* GetTestAxisX() { return m_testAxisX; }
    wxSpinCtrl* GetTestCountX() { return m_testCountX; }
    wxTextCtrl* GetTestDistanceX() { return m_testDistanceX; }
    wxStaticText* GetStaticText2101() { return m_staticText2101; }
    wxComboBox* GetTestFirstX() { return m_testFirstX; }
    wxStaticText* GetStaticText2151() { return m_staticText2151; }
    wxCheckBox* GetTestModeX() { return m_testModeX; }
    wxStaticText* GetTestDurationCounterX() { return m_testDurationCounterX; }
    wxStaticText* GetTestAxisY() { return m_testAxisY; }
    wxSpinCtrl* GetTestCountY() { return m_testCountY; }
    wxTextCtrl* GetTestDistanceY() { return m_testDistanceY; }
    wxStaticText* GetStaticText210115() { return m_staticText210115; }
    wxComboBox* GetTestFirstY() { return m_testFirstY; }
    wxStaticText* GetStaticText215123() { return m_staticText215123; }
    wxCheckBox* GetTestModeY() { return m_testModeY; }
    wxStaticText* GetTestDurationCounterY() { return m_testDurationCounterY; }
    wxStaticText* GetTestAxisZ() { return m_testAxisZ; }
    wxSpinCtrl* GetTestCountZ() { return m_testCountZ; }
    wxTextCtrl* GetTestDistanceZ() { return m_testDistanceZ; }
    wxStaticText* GetStaticText21011521() { return m_staticText21011521; }
    wxComboBox* GetTestFirstZ() { return m_testFirstZ; }
    wxStaticText* GetStaticText215124() { return m_staticText215124; }
    wxCheckBox* GetTestModeZ() { return m_testModeZ; }
    wxStaticText* GetTestDurationCounterZ() { return m_testDurationCounterZ; }
    wxPanel* GetTestIntervalPage() { return m_testIntervalPage; }
    wxStaticText* GetStaticText21174() { return m_staticText21174; }
    wxStaticLine* GetStaticLine22535() { return m_staticLine22535; }
    wxStaticText* GetStaticText2377() { return m_staticText2377; }
    wxStaticText* GetStaticText2418() { return m_staticText2418; }
    wxStaticText* GetStaticText2381() { return m_staticText2381; }
    wxStaticText* GetStaticText2379() { return m_staticText2379; }
    wxStaticText* GetStaticText2383() { return m_staticText2383; }
    wxCheckBox* GetTestDimTakeOverAndSave() { return m_testDimTakeOverAndSave; }
    wxStaticLine* GetStaticLine2385() { return m_staticLine2385; }
    wxStaticText* GetTestDimAxisX() { return m_testDimAxisX; }
    wxCheckBox* GetTestDimModeX() { return m_testDimModeX; }
    wxCheckBox* GetTestDimMinX() { return m_testDimMinX; }
    wxCheckBox* GetTestDimMaxX() { return m_testDimMaxX; }
    wxTextCtrl* GetTestDimResultX() { return m_testDimResultX; }
    wxStaticText* GetStaticText2431() { return m_staticText2431; }
    wxCheckBox* GetTestDimResultStateX() { return m_testDimResultStateX; }
    wxButton* GetTestDimTakeX() { return m_testDimTakeX; }
    wxStaticText* GetTestDimAxisY() { return m_testDimAxisY; }
    wxCheckBox* GetTestDimModeY() { return m_testDimModeY; }
    wxCheckBox* GetTestDimMinY() { return m_testDimMinY; }
    wxCheckBox* GetTestDimMaxY() { return m_testDimMaxY; }
    wxTextCtrl* GetTestDimResultY() { return m_testDimResultY; }
    wxStaticText* GetTestDimUnitX6() { return m_testDimUnitX6; }
    wxCheckBox* GetTestDimResultStateY() { return m_testDimResultStateY; }
    wxButton* GetTestDimTakeY() { return m_testDimTakeY; }
    wxStaticText* GetTestDimAxisZ() { return m_testDimAxisZ; }
    wxCheckBox* GetTestDimModeZ() { return m_testDimModeZ; }
    wxCheckBox* GetTestDimMinZ() { return m_testDimMinZ; }
    wxCheckBox* GetTestDimMaxZ() { return m_testDimMaxZ; }
    wxTextCtrl* GetTestDimResultZ() { return m_testDimResultZ; }
    wxStaticText* GetTestDimUnitX12() { return m_testDimUnitX12; }
    wxCheckBox* GetTestDimResultStateZ() { return m_testDimResultStateZ; }
    wxButton* GetTestDimTakeZ() { return m_testDimTakeZ; }
    wxStaticLine* GetStaticLine2429() { return m_staticLine2429; }
    wxButton* GetTestDimTakeAll() { return m_testDimTakeAll; }
    wxPanel* GetTestDimensions() { return m_testDimensions; }
    wxStaticText* GetStaticText21172() { return m_staticText21172; }
    wxStaticLine* GetStaticLine22533() { return m_staticLine22533; }
    wxToggleButton* GetTestToggleEndSwitch() { return m_testToggleEndSwitch; }
    wxPanel* GetTestLimitPage() { return m_testLimitPage; }
    wxStaticText* GetStaticText211726() { return m_staticText211726; }
    wxStaticLine* GetStaticLine225337() { return m_staticLine225337; }
    wxToggleButton* GetTestToggleTool() { return m_testToggleTool; }
    wxPanel* GetTestToolPage() { return m_testToolPage; }
    wxStaticText* GetStaticText21174365() { return m_staticText21174365; }
    wxTextCtrl* GetCtrlTestSelectedId() { return m_ctrlTestSelectedId; }
    wxStaticLine* GetStaticLine22535477() { return m_staticLine22535477; }
    wxStaticText* GetStaticText25139() { return m_staticText25139; }
    wxListBox* GetCtrlTestSelection() { return m_ctrlTestSelection; }
    wxScrolledWindow* GetScrollWin2571() { return m_scrollWin2571; }
    wxStaticText* GetStaticText251911() { return m_staticText251911; }
    wxTextCtrl* GetCtrlTestDescription() { return m_ctrlTestDescription; }
    wxStaticText* GetStaticText2486121314() { return m_staticText2486121314; }
    wxTextCtrl* GetCtrlTestParam1() { return m_ctrlTestParam1; }
    wxStaticText* GetStaticText24861216() { return m_staticText24861216; }
    wxTextCtrl* GetCtrlTestParam2() { return m_ctrlTestParam2; }
    wxStaticText* GetStaticText24861418() { return m_staticText24861418; }
    wxTextCtrl* GetCtrlTestParam3() { return m_ctrlTestParam3; }
    wxStaticText* GetStaticText24861520() { return m_staticText24861520; }
    wxTextCtrl* GetCtrlTestParam4() { return m_ctrlTestParam4; }
    wxStaticText* GetStaticText248622() { return m_staticText248622; }
    wxTextCtrl* GetCtrlTestParam5() { return m_ctrlTestParam5; }
    wxPanel* GetCtrlTestSuite() { return m_ctrlTestSuite; }
    wxTreebook* GetTreebookTest() { return m_treebookTest; }
    wxPanel* GetPanelTesting() { return m_panelTesting; }
    wxCheckBox* GetCheckManuallyXY() { return m_checkManuallyXY; }
    wxStaticText* GetStaticText1160() { return m_staticText1160; }
    wxStaticLine* GetStaticLine1162() { return m_staticLine1162; }
    wxRadioBox* GetMmRadioCoordinates() { return m_mmRadioCoordinates; }
    wxStaticText* GetStaticText799() { return m_staticText799; }
    wxComboBox* GetMetricZ() { return m_metricZ; }
    wxStaticText* GetStaticText793() { return m_staticText793; }
    wxButton* GetMinManuallyXSlider() { return m_minManuallyXSlider; }
    wxTextCtrl* GetMetricX() { return m_metricX; }
    wxButton* GetMaxManuallyXSlider() { return m_maxManuallyXSlider; }
    wxButton* GetZeroManuallyXSlider() { return m_zeroManuallyXSlider; }
    wxButton* GetSignManuallyXSlider() { return m_signManuallyXSlider; }
    wxStaticText* GetMmUnitX() { return m_mmUnitX; }
    wxSlider* GetXManuallySlider() { return m_xManuallySlider; }
    wxStaticText* GetStaticText797() { return m_staticText797; }
    wxButton* GetMinManuallyYSlider() { return m_minManuallyYSlider; }
    wxTextCtrl* GetMetricY() { return m_metricY; }
    wxButton* GetMaxManuallyYSlider() { return m_maxManuallyYSlider; }
    wxButton* GetZeroManuallyYSlider() { return m_zeroManuallyYSlider; }
    wxButton* GetSignManuallyYSlider() { return m_signManuallyYSlider; }
    wxStaticText* GetMmUnitY() { return m_mmUnitY; }
    wxSlider* GetYManuallySlider() { return m_yManuallySlider; }
    wxStaticText* GetStaticText2073() { return m_staticText2073; }
    wxStaticLine* GetStaticLine2047() { return m_staticLine2047; }
    wxCheckBox* GetCheckManuallyZ() { return m_checkManuallyZ; }
    wxStaticText* GetStaticText2075() { return m_staticText2075; }
    wxStaticText* GetStaticText7973() { return m_staticText7973; }
    wxButton* GetMinManuallyZSlider() { return m_minManuallyZSlider; }
    wxTextCtrl* GetMetricZEdit() { return m_metricZEdit; }
    wxButton* GetMaxManuallyZSlider() { return m_maxManuallyZSlider; }
    wxButton* GetZeroManuallyZSlider() { return m_zeroManuallyZSlider; }
    wxButton* GetSignManuallyZSlider() { return m_signManuallyZSlider; }
    wxStaticText* GetMmUnitZ() { return m_mmUnitZ; }
    wxSlider* GetZManuallySlider() { return m_zManuallySlider; }
    wxPanel* GetPanelManually() { return m_panelManually; }
    wxButton* GetOpenSourceExtern() { return m_openSourceExtern; }
    wxButton* GetOpenSvgExtern() { return m_openSvgExtern; }
    wxButton* GetBtPathGenerator() { return m_btPathGenerator; }
    wxButton* GetSaveTemplate() { return m_saveTemplate; }
    wxButton* GetReloadTemplate() { return m_reloadTemplate; }
    wxBitmapToggleButton* GetBtSvgToggleWordWrap() { return m_btSvgToggleWordWrap; }
    wxBitmapToggleButton* GetPreviewErrorInfo() { return m_previewErrorInfo; }
    wxStyledTextCtrl* GetStcFileContent() { return m_stcFileContent; }
    wxBitmapToggleButton* GetTbCaseSensitive() { return m_tbCaseSensitive; }
    wxBitmapToggleButton* GetTbWholeWord() { return m_tbWholeWord; }
    wxBitmapToggleButton* GetTbRegEx() { return m_tbRegEx; }
    wxBitmapToggleButton* GetTbHighLight() { return m_tbHighLight; }
    wxStaticBitmap* GetSvgEditSearchState() { return m_svgEditSearchState; }
    wxComboBox* GetSvgEditSearch() { return m_svgEditSearch; }
    wxButton* GetSvgEditFind() { return m_svgEditFind; }
    wxButton* GetSvgEditFindPrev() { return m_svgEditFindPrev; }
    wxStaticText* GetFilePosition() { return m_filePosition; }
    wxTextCtrl* GetSvgEditStatus() { return m_svgEditStatus; }
    wxStaticText* GetEditMode() { return m_editMode; }
    wxPanel* GetPanelTplEdit() { return m_panelTplEdit; }
    wxStaticText* GetStaticText1498() { return m_staticText1498; }
    wxDataViewListCtrl* GetDvListCtrlSvgUAInboundPathList() { return m_dvListCtrlSvgUAInboundPathList; }
    wxStaticText* GetStaticText14983() { return m_staticText14983; }
    wxDataViewListCtrl* GetDvListCtrlSvgUAUseDirective() { return m_dvListCtrlSvgUAUseDirective; }
    wxStaticText* GetStaticText1500() { return m_staticText1500; }
    wxDataViewListCtrl* GetDvListCtrlSvgUADetailInfo() { return m_dvListCtrlSvgUADetailInfo; }
    wxTextCtrl* GetSelectedUAInfo() { return m_selectedUAInfo; }
    wxPanel* GetPanelTplUserAgent() { return m_panelTplUserAgent; }
    wxStaticText* GetStaticText1370() { return m_staticText1370; }
    wxStaticText* GetStaticText1571() { return m_staticText1571; }
    wxStaticText* GetDebugPhase() { return m_debugPhase; }
    wxDataViewListCtrl* GetDvListCtrlSvgDebuggerInfoBase() { return m_dvListCtrlSvgDebuggerInfoBase; }
    wxStaticText* GetStaticText1372() { return m_staticText1372; }
    wxStaticText* GetStaticText1374() { return m_staticText1374; }
    wxDataViewListCtrl* GetDvListCtrlSvgDebuggerInfoPath() { return m_dvListCtrlSvgDebuggerInfoPath; }
    wxDataViewListCtrl* GetDvListCtrlSvgDebuggerInfoDetail() { return m_dvListCtrlSvgDebuggerInfoDetail; }
    wxTextCtrl* GetSvgDebuggerKey() { return m_svgDebuggerKey; }
    wxTextCtrl* GetSvgDebuggerValue() { return m_svgDebuggerValue; }
    wxPanel* GetPanelTplDebugger() { return m_panelTplDebugger; }
    wxStaticText* GetSvgFilePreviewHint() { return m_svgFilePreviewHint; }
    wxWebView* GetSvgPreview() { return m_svgPreview; }
    wxPanel* GetPanelTplPreview() { return m_panelTplPreview; }
    wxNotebook* GetTemplateNotebook() { return m_templateNotebook; }
    wxPanel* GetPanelTemplateContent() { return m_panelTemplateContent; }
    wxNotebook* GetMainNotebook() { return m_mainNotebook; }
    wxScrolledWindow* GetScrollWinMain() { return m_scrollWinMain; }
    wxStaticText* GetStaticText28052() { return m_staticText28052; }
    CncSpeedView* GetSpeedView() { return m_speedView; }
    wxPanel* GetPanelSpeed() { return m_panelSpeed; }
    wxStaticText* GetStaticText1644() { return m_staticText1644; }
    wxListBox* GetLruList() { return m_lruList; }
    wxPanel* GetLruPanel() { return m_lruPanel; }
    wxButton* GetBtDefaultDir() { return m_btDefaultDir; }
    wxButton* GetBtCurrentFile() { return m_btCurrentFile; }
    wxStaticText* GetStaticText1647() { return m_staticText1647; }
    wxGenericDirCtrl* GetDirCtrl() { return m_dirCtrl; }
    wxPanel* GetStdPanel() { return m_stdPanel; }
    wxToolbook* GetTemplateToolbook() { return m_templateToolbook; }
    wxScrolledWindow* GetScrollWinFile() { return m_scrollWinFile; }
    wxBitmapButton* GetClearLogger() { return m_clearLogger; }
    wxBitmapButton* GetFreezeLogger() { return m_freezeLogger; }
    wxBitmapButton* GetCopyLogger() { return m_copyLogger; }
    wxCheckBox* GetShowLoggerOnDemand() { return m_showLoggerOnDemand; }
    wxTextCtrl* GetLogger() { return m_logger; }
    wxPanel* GetPanel3157() { return m_panel3157; }
    wxToolbook* GetLoggerToolbook() { return m_loggerToolbook; }
    wxTextCtrl* GetTmpTraceInfo() { return m_tmpTraceInfo; }
    wxScrolledWindow* GetScrollWinLogger() { return m_scrollWinLogger; }
    wxStaticText* GetStaticText3952() { return m_staticText3952; }
    wxTextCtrl* GetCmdCount() { return m_cmdCount; }
    wxStaticText* GetStaticText395() { return m_staticText395; }
    wxTextCtrl* GetCmdDuration() { return m_cmdDuration; }
    wxStaticLine* GetStaticLine602() { return m_staticLine602; }
    wxTextCtrl* GetInputFileName() { return m_inputFileName; }
    wxStaticLine* GetStaticLine6801() { return m_staticLine6801; }
    wxStaticText* GetSvgParseMode() { return m_svgParseMode; }
    wxPanel* GetActivityPanel() { return m_activityPanel; }
    wxStaticLine* GetStaticLine680() { return m_staticLine680; }
    wxStaticText* GetLableX() { return LableX; }
    wxTextCtrl* GetXAxis() { return m_xAxis; }
    wxTextCtrl* GetXAxisCtl() { return m_xAxisCtl; }
    wxStaticText* GetLabelY() { return LabelY; }
    wxTextCtrl* GetYAxis() { return m_yAxis; }
    wxTextCtrl* GetYAxisCtl() { return m_yAxisCtl; }
    wxStaticText* GetLableZ() { return LableZ; }
    wxTextCtrl* GetZAxis() { return m_zAxis; }
    wxTextCtrl* GetZAxisCtl() { return m_zAxisCtl; }
    wxStaticLine* GetStaticLine60234() { return m_staticLine60234; }
    wxStaticText* GetStaticText1196() { return m_staticText1196; }
    wxStaticText* GetXMinLimit() { return m_xMinLimit; }
    wxStaticText* GetXMaxLimit() { return m_xMaxLimit; }
    wxStaticText* GetYMinLimit() { return m_yMinLimit; }
    wxStaticText* GetYMaxLimit() { return m_yMaxLimit; }
    wxStaticText* GetZMinLimit() { return m_zMinLimit; }
    wxStaticText* GetZMaxLimit() { return m_zMaxLimit; }
    wxStaticLine* GetStaticLine602341() { return m_staticLine602341; }
    wxStaticText* GetStaticText2199() { return m_staticText2199; }
    wxStaticBitmap* GetRefPosTrafficLight() { return m_refPosTrafficLight; }
    wxStaticLine* GetStaticLine6023412() { return m_staticLine6023412; }
    wxScrolledWindow* GetStatusBar() { return m_statusBar; }
    wxStaticText* GetStaticText11481() { return m_staticText11481; }
    wxDataViewListCtrl* GetDvListCtrlConfigSummary() { return m_dvListCtrlConfigSummary; }
    wxButton* GetBtCancelRun() { return m_btCancelRun; }
    wxButton* GetBtConfirmRun() { return m_btConfirmRun; }
    wxPanel* GetPanel2601() { return m_panel2601; }
    wxStaticText* GetStaticText1148() { return m_staticText1148; }
    wxStaticText* GetStaticText1150() { return m_staticText1150; }
    wxButton* GetButton1473() { return m_button1473; }
    wxDataViewListCtrl* GetDvListCtrlLastSetters() { return m_dvListCtrlLastSetters; }
    wxDataViewListCtrl* GetDvListCtrlProcessedSetters() { return m_dvListCtrlProcessedSetters; }
    wxPanel* GetCncSetters() { return m_cncSetters; }
    wxStaticText* GetStaticText1283() { return m_staticText1283; }
    wxStaticText* GetStaticText1281() { return m_staticText1281; }
    wxDataViewListCtrl* GetDvListCtrlStatic() { return m_dvListCtrlStatic; }
    wxDataViewListCtrl* GetDvListCtrlDynamic() { return m_dvListCtrlDynamic; }
    wxPanel* GetCncConfiguration() { return m_cncConfiguration; }
    wxStaticText* GetStaticText12831() { return m_staticText12831; }
    wxButton* GetBtRequestCtlConfig() { return m_btRequestCtlConfig; }
    wxDataViewListCtrl* GetDvListCtrlControllerConfig() { return m_dvListCtrlControllerConfig; }
    wxPanel* GetControllerConfiguration() { return m_controllerConfiguration; }
    wxStaticText* GetStaticText128313() { return m_staticText128313; }
    wxButton* GetBtRequestCtlPins() { return m_btRequestCtlPins; }
    wxDataViewListCtrl* GetDvListCtrlControllerPins() { return m_dvListCtrlControllerPins; }
    wxPanel* GetControllerPinReport() { return m_controllerPinReport; }
    wxStaticText* GetStaticText1283132() { return m_staticText1283132; }
    wxButton* GetBtClearMsgHistory() { return m_btClearMsgHistory; }
    wxTextCtrl* GetControllerMsgHistory() { return m_controllerMsgHistory; }
    wxPanel* GetConrollerMessages() { return m_conrollerMessages; }
    wxStaticText* GetStaticText128314() { return m_staticText128314; }
    wxButton* GetBtRequestCtlErrorInfo() { return m_btRequestCtlErrorInfo; }
    wxDataViewListCtrl* GetDvListCtrlControllerErrorInfo() { return m_dvListCtrlControllerErrorInfo; }
    wxPanel* GetControllerErrorInfo() { return m_controllerErrorInfo; }
    wxListbook* GetNotebookConfig() { return m_notebookConfig; }
    wxPanel* GetCncParameters() { return m_cncParameters; }
    wxStaticText* GetStaticText1048() { return m_staticText1048; }
    CncZView* GetZView() { return m_zView; }
    wxStaticText* GetInfoToolDiameter() { return m_infoToolDiameter; }
    wxStaticBitmap* GetStaticBitmap2401() { return m_staticBitmap2401; }
    wxStaticBitmap* GetToolStateTrafficLight() { return m_toolStateTrafficLight; }
    wxStaticText* GetStaticText16032() { return m_staticText16032; }
    wxComboBox* GetCbCurveLibResolution() { return m_cbCurveLibResolution; }
    wxBitmapToggleButton* GetSwitchCoordType() { return m_switchCoordType; }
    wxBitmapToggleButton* GetSwitchMonitoing() { return m_switchMonitoing; }
    wxBitmapToggleButton* GetGridDrawPane() { return m_gridDrawPane; }
    wxButton* GetTraceDrawPane() { return m_traceDrawPane; }
    wxButton* GetClearDrawPane() { return m_clearDrawPane; }
    wxStaticText* GetStaticText1054() { return m_staticText1054; }
    wxComboBox* GetCbUpdateInterval() { return m_cbUpdateInterval; }
    wxPanel* GetPanel3281() { return m_panel3281; }
    wxPanel* GetYAxisMarker() { return m_yAxisMarker; }
    wxPanel* GetPanel32812() { return m_panel32812; }
    wxPanel* GetXAxisMarkerTop() { return m_xAxisMarkerTop; }
    wxPanel* GetDrawPane() { return m_drawPane; }
    wxPanel* GetXAxisMarkerBottom() { return m_xAxisMarkerBottom; }
    wxScrolledWindow* GetDrawPaneWindow() { return m_drawPaneWindow; }
    wxStaticText* GetStaticText1950() { return m_staticText1950; }
    wxComboBox* GetGridPosUnit() { return m_gridPosUnit; }
    wxStaticText* GetStaticText3169() { return m_staticText3169; }
    wxComboBox* GetCbDrawPaneZoom() { return m_cbDrawPaneZoom; }
    wxStaticText* GetStaticText1943() { return m_staticText1943; }
    wxTextCtrl* GetDrawPainPositionX() { return m_drawPainPositionX; }
    wxStaticText* GetStaticText19431() { return m_staticText19431; }
    wxTextCtrl* GetDrawPainPositionY() { return m_drawPainPositionY; }
    wxStaticText* GetStaticText1128() { return m_staticText1128; }
    wxTextCtrl* GetCrossings() { return m_crossings; }
    wxStaticText* GetStaticText1966() { return m_staticText1966; }
    wxTextCtrl* GetPassingCount() { return m_passingCount; }
    wxStaticText* GetStaticText1696() { return m_staticText1696; }
    wxStaticText* GetMinPosX() { return m_minPosX; }
    wxStaticText* GetMinPosY() { return m_minPosY; }
    wxStaticText* GetMinPosZ() { return m_minPosZ; }
    wxStaticText* GetStaticText1694() { return m_staticText1694; }
    wxStaticText* GetMaxPosX() { return m_maxPosX; }
    wxStaticText* GetMaxPosY() { return m_maxPosY; }
    wxStaticText* GetMaxPosZ() { return m_maxPosZ; }
    wxPanel* GetOutPanel() { return m_outPanel; }
    wxButton* Get3D_Animate() { return m_3D_Animate; }
    wxButton* Get3D_Refreh() { return m_3D_Refreh; }
    wxButton* Get3D_Clear() { return m_3D_Clear; }
    wxStaticLine* GetStaticLine2348() { return m_staticLine2348; }
    wxButton* Get3D_Top() { return m_3D_Top; }
    wxButton* Get3D_Bottom() { return m_3D_Bottom; }
    wxButton* Get3D_Front() { return m_3D_Front; }
    wxButton* Get3D_Rear() { return m_3D_Rear; }
    wxButton* Get3D_Left() { return m_3D_Left; }
    wxButton* Get3D_Right4() { return m_3D_Right4; }
    wxButton* Get3D_Perspective() { return m_3D_Perspective; }
    wxStaticLine* GetStaticLine2341() { return m_staticLine2341; }
    wxButton* GetButton2345() { return m_button2345; }
    wxStaticLine* GetStaticLine2343() { return m_staticLine2343; }
    wxStaticText* GetStaticText2329() { return m_staticText2329; }
    wxStaticText* GetStaticText2331() { return m_staticText2331; }
    wxStaticText* GetStaticText2333() { return m_staticText2333; }
    wxPanel* GetDrawPane3D() { return m_drawPane3D; }
    wxTextCtrl* GetTrace3D() { return m_trace3D; }
    wxStaticText* GetStaticText3133() { return m_staticText3133; }
    wxCheckBox* GetCb3DDrawZeroPlane() { return m_cb3DDrawZeroPlane; }
    wxCheckBox* GetCb3DDrawWorkpieceSurfacePlane() { return m_cb3DDrawWorkpieceSurfacePlane; }
    wxCheckBox* GetCb3DDrawWorkpieceOffset() { return m_cb3DDrawWorkpieceOffset; }
    wxStaticLine* GetStaticLine3129() { return m_staticLine3129; }
    wxComboBox* GetPlaneSelect3D() { return m_planeSelect3D; }
    wxStaticText* GetStaticText268320() { return m_staticText268320; }
    wxSpinCtrl* GetSpin3DAngelX() { return m_spin3DAngelX; }
    wxStaticText* GetStaticText268522() { return m_staticText268522; }
    wxSpinCtrl* GetSpin3DAngelY() { return m_spin3DAngelY; }
    wxStaticText* GetStaticText268118() { return m_staticText268118; }
    wxSpinCtrl* GetSpin3DAngelZ() { return m_spin3DAngelZ; }
    wxButton* GetButton2710() { return m_button2710; }
    wxPanel* GetPanel2696() { return m_panel2696; }
    wxPanel* GetPanel2590() { return m_panel2590; }
    wxPanel* Get3DPane() { return m_3DPane; }
    wxButton* GetSvgEmuOpenFileAsSource() { return m_svgEmuOpenFileAsSource; }
    wxButton* GetSvgEmuOpenFileAsSvg() { return m_svgEmuOpenFileAsSvg; }
    wxButton* GetSvgEmuReload() { return m_svgEmuReload; }
    wxButton* GetSvgEmuClear() { return m_svgEmuClear; }
    wxBitmapToggleButton* GetSwitchCoordTypeSvgOut() { return m_switchCoordTypeSvgOut; }
    wxButton* GetSvgEmuToggleOrigPath() { return m_svgEmuToggleOrigPath; }
    wxButton* GetSvgEmuZoomHome() { return m_svgEmuZoomHome; }
    wxButton* GetSvgEmuZoomMinus() { return m_svgEmuZoomMinus; }
    wxButton* GetSvgEmuZoomPlus() { return m_svgEmuZoomPlus; }
    wxWebView* GetSvgView() { return m_svgView; }
    wxPanel* GetSvgEmuResult() { return m_svgEmuResult; }
    wxBitmapToggleButton* GetSvgEmuToggleWordWrap() { return m_svgEmuToggleWordWrap; }
    wxStyledTextCtrl* GetStcEmuSource() { return m_stcEmuSource; }
    wxPanel* GetSvgEmuSource() { return m_svgEmuSource; }
    wxBitmapButton* GetOpenXmlTraceAsText() { return m_openXmlTraceAsText; }
    wxBitmapButton* GetOpenXmlTrace() { return m_openXmlTrace; }
    wxBitmapButton* GetCopySvgTrace() { return m_copySvgTrace; }
    wxWebView* GetSvgTrace() { return m_svgTrace; }
    wxPanel* GetSvgTracePreview() { return m_svgTracePreview; }
    wxNotebook* GetOutboundNotebook() { return m_outboundNotebook; }
    wxScrolledWindow* GetScrollOutbound() { return m_scrollOutbound; }
    wxButton* GetEnableSerialSpy() { return m_enableSerialSpy; }
    wxButton* GetMarkSerialSpy() { return m_MarkSerialSpy; }
    wxButton* GetClearSerialSpy() { return m_clearSerialSpy; }
    wxCheckBox* GetClearSerialSpyOnConnect() { return m_clearSerialSpyOnConnect; }
    wxTextCtrl* GetSerialSpy() { return m_serialSpy; }
    wxStaticText* GetStaticText27519() { return m_staticText27519; }
    wxTextCtrl* GetSerialSpyDetails() { return m_serialSpyDetails; }
    wxScrolledWindow* GetScrollSpy() { return m_scrollSpy; }
    wxStaticText* GetStaticText3261() { return m_staticText3261; }
    wxComboBox* GetCbUCUnitFrom() { return m_cbUCUnitFrom; }
    wxStaticText* GetStaticText3259() { return m_staticText3259; }
    wxComboBox* GetCbUCUnitTo() { return m_cbUCUnitTo; }
    wxTextCtrl* GetCbUCValueFrom() { return m_cbUCValueFrom; }
    wxTextCtrl* GetCbUCValueTo() { return m_cbUCValueTo; }
    wxButton* GetBtUCClose() { return m_btUCClose; }
    wxPanel* GetSvgUnitCalulator() { return m_svgUnitCalulator; }
    wxAuiManager* GetAuimgrMain() { return m_auimgrMain; }
    wxMenuBar* GetMenuBar() { return m_menuBar; }
    wxTimer* GetStartupTimer() { return m_startupTimer; }
    wxTimer* GetSerialTimer() { return m_serialTimer; }
    wxTimer* GetTraceTimer() { return m_traceTimer; }
    MainFrameBClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("CNC Controller"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(1000,700), long style = wxDEFAULT_FRAME_STYLE);
    virtual ~MainFrameBClass();
};


class PathGeneratorFrameBase : public wxFrame
{
protected:
    wxFlexGridSizer* flexGridSizer980;
    wxSplitterWindow* m_splitter3185;
    wxPanel* m_splitterPage3189;
    wxFlexGridSizer* flexGridSizer973;
    wxFlexGridSizer* flexGridSizer3093;
    wxStaticText* m_staticText3095;
    wxComboBox* m_pgPathSelector;
    wxFlexGridSizer* flexGridSizer2825;
    wxSplitterWindow* m_splitter2932;
    wxPanel* m_splitterPage2936;
    wxFlexGridSizer* flexGridSizer2942;
#if wxUSE_WEBVIEW
    wxWebView* m_pgPreview;
#endif // wxUSE_WEBVIEW

    wxPanel* m_splitterPage2940;
    wxFlexGridSizer* flexGridSizer2944;
    wxToolbook* m_toolbook3227;
    wxPanel* m_panel3229;
    wxFlexGridSizer* flexGridSizer3233;
    wxTextCtrl* m_generatedPreview;
    wxPanel* m_panel3231;
    wxFlexGridSizer* flexGridSizer3235;
    wxTextCtrl* m_generatedResult;
    wxPanel* m_splitterPage3193;
    wxFlexGridSizer* flexGridSizer986;
    wxFlexGridSizer* flexGridSizer2874;
    wxButton* m_btPGGenerate;
    wxButton* m_btPGClear;
    wxButton* m_btPGReplaceEdit;
    wxButton* m_btPGCopy;
    wxFlexGridSizer* flexGridSizer3225;
    wxButton* m_btPGMinimize;
    wxButton* m_btPGClose;
    wxFlexGridSizer* flexGridSizer2972;
    wxPropertyGridManager* m_pgParameterMgr;
    wxPGProperty* m_pgCatCommon;
    wxPGProperty* m_pgPropToolDiameter;
    wxPGProperty* m_pgPropCorrection;
    wxPGProperty* m_pgPropPathColour;
    wxPGProperty* m_pgPropConfigBlock;
    wxPGProperty* m_pgCatPath;
    wxPGProperty* m_pgProp01;
    wxPGProperty* m_pgCatGrid;
    wxPGProperty* m_pgPropRefCross;
    wxPGProperty* m_pgPropGridDisplay;
    wxPGProperty* m_pgPropGridSize;
    wxPGProperty* m_pgCatCncBlock;
    wxPGProperty* m_pgPropCncInclude;
    wxPGProperty* m_pgCatCncParameter;
    wxPGProperty* m_pgPropCncZDepthMode;
    wxPGProperty* m_pgPropCncZDepth;
    wxPGProperty* m_pgPropCncToolCorrection;
    wxPGProperty* m_pgPropCncReversePath;
    wxPGProperty* m_pgCatSvg;
    wxPGProperty* m_pgPropSvgWidth;
    wxPGProperty* m_pgPropSvgHeight;
    wxPGProperty* m_pgCatViewBox;
    wxPGProperty* m_pgPropSvgVbX;
    wxPGProperty* m_pgPropSvgVbY;
    wxPGProperty* m_pgPropSvgVbW;
    wxPGProperty* m_pgPropSvgVbH;
    wxPGProperty* m_pgCatTransform;
    wxPGProperty* m_pgPropTransformMode;
    wxPGProperty* m_pgCatTranslate;
    wxPGProperty* m_pgPropTranslateX;
    wxPGProperty* m_pgPropTranslateY;
    wxPGProperty* m_pgCatScale;
    wxPGProperty* m_pgPropScaleX;
    wxPGProperty* m_pgPropScaleY;
    wxPGProperty* m_pgCatRotate;
    wxPGProperty* m_pgPropRotateA;
    wxPGProperty* m_pgPropRotateX;
    wxPGProperty* m_pgPropRotateY;
    wxPGProperty* m_pgCatSkrew;
    wxPGProperty* m_pgPropSkewX;
    wxPGProperty* m_pgPropSkewY;

protected:
    virtual void onCloseWindow(wxCloseEvent& event) { event.Skip(); }
    virtual void onSize(wxSizeEvent& event) { event.Skip(); }
    virtual void onActivate(wxActivateEvent& event) { event.Skip(); }
    virtual void selectPathSelector(wxCommandEvent& event) { event.Skip(); }
    #if wxUSE_WEBVIEW
    #endif // wxUSE_WEBVIEW
    virtual void generatePath(wxCommandEvent& event) { event.Skip(); }
    virtual void clearView(wxCommandEvent& event) { event.Skip(); }
    virtual void relaceEditControlSelection(wxCommandEvent& event) { event.Skip(); }
    virtual void copyPath(wxCommandEvent& event) { event.Skip(); }
    virtual void toogleSize(wxCommandEvent& event) { event.Skip(); }
    virtual void onCloseWindowFromButton(wxCommandEvent& event) { event.Skip(); }
    virtual void propertyChanged(wxPropertyGridEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText3095() { return m_staticText3095; }
    wxComboBox* GetPgPathSelector() { return m_pgPathSelector; }
    wxWebView* GetPgPreview() { return m_pgPreview; }
    wxPanel* GetSplitterPage2936() { return m_splitterPage2936; }
    wxTextCtrl* GetGeneratedPreview() { return m_generatedPreview; }
    wxPanel* GetPanel3229() { return m_panel3229; }
    wxTextCtrl* GetGeneratedResult() { return m_generatedResult; }
    wxPanel* GetPanel3231() { return m_panel3231; }
    wxToolbook* GetToolbook3227() { return m_toolbook3227; }
    wxPanel* GetSplitterPage2940() { return m_splitterPage2940; }
    wxSplitterWindow* GetSplitter2932() { return m_splitter2932; }
    wxPanel* GetSplitterPage3189() { return m_splitterPage3189; }
    wxButton* GetBtPGGenerate() { return m_btPGGenerate; }
    wxButton* GetBtPGClear() { return m_btPGClear; }
    wxButton* GetBtPGReplaceEdit() { return m_btPGReplaceEdit; }
    wxButton* GetBtPGCopy() { return m_btPGCopy; }
    wxButton* GetBtPGMinimize() { return m_btPGMinimize; }
    wxButton* GetBtPGClose() { return m_btPGClose; }
    wxPropertyGridManager* GetPgParameterMgr() { return m_pgParameterMgr; }
    wxPanel* GetSplitterPage3193() { return m_splitterPage3193; }
    wxSplitterWindow* GetSplitter3185() { return m_splitter3185; }
    PathGeneratorFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("SVG Path Generator"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(600,750), long style = wxDEFAULT_FRAME_STYLE|wxFRAME_FLOAT_ON_PARENT);
    virtual ~PathGeneratorFrameBase();
};


class EndSwitchDialogBase : public wxDialog
{
protected:
    wxFlexGridSizer* flexGridSizer1529;
    wxFlexGridSizer* flexGridSizer1531;
    wxTextCtrl* m_limitInfo;
    wxStaticText* m_staticText1547;
    wxFlexGridSizer* flexGridSizer1533;
    wxRadioBox* m_XAxisEndSwitchBox;
    wxRadioBox* m_YAxisEndSwitchBox;
    wxRadioBox* m_ZAxisEndSwitchBox;
    wxButton* m_btDissolveX;
    wxButton* m_btDissolveY;
    wxButton* m_btDissolveZ;
    wxFlexGridSizer* flexGridSizer1535;
    wxButton* m_btCancle;

protected:
    virtual void selectX(wxCommandEvent& event) { event.Skip(); }
    virtual void selectY(wxCommandEvent& event) { event.Skip(); }
    virtual void selectZ(wxCommandEvent& event) { event.Skip(); }
    virtual void dissolveX(wxCommandEvent& event) { event.Skip(); }
    virtual void dissolveY(wxCommandEvent& event) { event.Skip(); }
    virtual void dissolveZ(wxCommandEvent& event) { event.Skip(); }
    virtual void cancle(wxCommandEvent& event) { event.Skip(); }

public:
    wxTextCtrl* GetLimitInfo() { return m_limitInfo; }
    wxStaticText* GetStaticText1547() { return m_staticText1547; }
    wxRadioBox* GetXAxisEndSwitchBox() { return m_XAxisEndSwitchBox; }
    wxRadioBox* GetYAxisEndSwitchBox() { return m_YAxisEndSwitchBox; }
    wxRadioBox* GetZAxisEndSwitchBox() { return m_ZAxisEndSwitchBox; }
    wxButton* GetBtDissolveX() { return m_btDissolveX; }
    wxButton* GetBtDissolveY() { return m_btDissolveY; }
    wxButton* GetBtDissolveZ() { return m_btDissolveZ; }
    wxButton* GetBtCancle() { return m_btCancle; }
    EndSwitchDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Manual end switch dissolving"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(400,320), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~EndSwitchDialogBase();
};


class ImageLib16 : public wxImageList
{
protected:
    // Maintain a map of all bitmaps representd by their name
    std::map<wxString, wxBitmap> m_bitmaps;
    // The requested image resolution (can be one of @2x, @1.5x, @1.25x or an empty string (the default)
    wxString m_resolution;
    int m_imagesWidth;
    int m_imagesHeight;


protected:

public:
    ImageLib16();
    const wxBitmap& Bitmap(const wxString &name) const {
        if ( !m_bitmaps.count(name + m_resolution) )
            return wxNullBitmap;
        return m_bitmaps.find(name + m_resolution)->second;
    }

    void SetBitmapResolution(const wxString &res = wxEmptyString) {
        m_resolution = res;
    }

    virtual ~ImageLib16();
};


class ImageLib24 : public wxImageList
{
protected:
    // Maintain a map of all bitmaps representd by their name
    std::map<wxString, wxBitmap> m_bitmaps;
    // The requested image resolution (can be one of @2x, @1.5x, @1.25x or an empty string (the default)
    wxString m_resolution;
    int m_imagesWidth;
    int m_imagesHeight;


protected:

public:
    ImageLib24();
    const wxBitmap& Bitmap(const wxString &name) const {
        if ( !m_bitmaps.count(name + m_resolution) )
            return wxNullBitmap;
        return m_bitmaps.find(name + m_resolution)->second;
    }

    void SetBitmapResolution(const wxString &res = wxEmptyString) {
        m_resolution = res;
    }

    virtual ~ImageLib24();
};


class ImageLibBig : public wxImageList
{
protected:
    // Maintain a map of all bitmaps representd by their name
    std::map<wxString, wxBitmap> m_bitmaps;
    // The requested image resolution (can be one of @2x, @1.5x, @1.25x or an empty string (the default)
    wxString m_resolution;
    int m_imagesWidth;
    int m_imagesHeight;


protected:

public:
    ImageLibBig();
    const wxBitmap& Bitmap(const wxString &name) const {
        if ( !m_bitmaps.count(name + m_resolution) )
            return wxNullBitmap;
        return m_bitmaps.find(name + m_resolution)->second;
    }

    void SetBitmapResolution(const wxString &res = wxEmptyString) {
        m_resolution = res;
    }

    virtual ~ImageLibBig();
};

#endif
