//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxCrafterUnitTest.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CNCGUICONTROLLER_CNCCONTROLERGUI_WXCRAFTERUNITTEST_BASE_CLASSES_H
#define _CNCGUICONTROLLER_CNCCONTROLERGUI_WXCRAFTERUNITTEST_BASE_CLASSES_H

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/combobox.h>
#include <wx/arrstr.h>
#include <wx/button.h>
#include <wx/textctrl.h>
#include <wx/checkbox.h>
#include <wx/timer.h>
#include <wx/listbook.h>
#include <wx/panel.h>
#include <wx/imaglist.h>
#include <wx/spinctrl.h>
#include <wx/filepicker.h>
#include <wx/statline.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class CncUnitTestsBase : public wxDialog
{
protected:
    wxStaticText* m_staticText3357;
    wxComboBox* m_unitTestSelector;
    wxButton* m_btUnitTestClear;
    wxButton* m_btUnitTestRun;
    wxTextCtrl* m_testResultStreamPlaceholder;
    wxStaticText* m_unitTestStatus;
    wxCheckBox* m_unitTestFreezeOutput;
    wxCheckBox* m_unitTestAutoRun;
    wxTimer* m_unitTestStartupTimer;

protected:
    virtual void onShow(wxShowEvent& event)
    {
	event.Skip();
    }
    virtual void selectTest(wxCommandEvent& event)
    {
	event.Skip();
    }
    virtual void clearView(wxCommandEvent& event)
    {
	event.Skip();
    }
    virtual void onStartupTimer(wxTimerEvent& event)
    {
	event.Skip();
    }

public:
    wxStaticText* GetStaticText3357()
    {
	return m_staticText3357;
    }
    wxComboBox* GetUnitTestSelector()
    {
	return m_unitTestSelector;
    }
    wxButton* GetBtUnitTestClear()
    {
	return m_btUnitTestClear;
    }
    wxButton* GetBtUnitTestRun()
    {
	return m_btUnitTestRun;
    }
    wxTextCtrl* GetTestResultStreamPlaceholder()
    {
	return m_testResultStreamPlaceholder;
    }
    wxStaticText* GetUnitTestStatus()
    {
	return m_unitTestStatus;
    }
    wxCheckBox* GetUnitTestFreezeOutput()
    {
	return m_unitTestFreezeOutput;
    }
    wxCheckBox* GetUnitTestAutoRun()
    {
	return m_unitTestAutoRun;
    }
    wxTimer* GetUnitTestStartupTimer()
    {
	return m_unitTestStartupTimer;
    }
    CncUnitTestsBase(wxWindow* parent,
        wxWindowID id = wxID_ANY,
        const wxString& title = _("CNC Controller Unit Tests . . ."),
        const wxPoint& pos = wxDefaultPosition,
        const wxSize& size = wxSize(800, 600),
        long style = wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER | wxMAXIMIZE_BOX | wxSYSTEM_MENU | wxCLOSE_BOX);
    virtual ~CncUnitTestsBase();
};

class CncTestRunConfigBase : public wxDialog
{
protected:
    wxListbook* m_lbTestCase;
    wxPanel* m_plLoop;
    wxStaticText* m_staticText352;
    wxSpinCtrl* m_loopCount;
    wxStaticText* m_staticText35;
    wxCheckBox* m_cbBreakOnError;
    wxPanel* m_plDir;
    wxStaticText* m_staticText33;
    wxDirPickerCtrl* m_dirSelection;
    wxStaticLine* m_staticLine43;
    wxButton* m_btCancel;
    wxButton* m_btRun;

protected:
    virtual void onCancel(wxCommandEvent& event)
    {
	event.Skip();
    }
    virtual void onRun(wxCommandEvent& event)
    {
	event.Skip();
    }

public:
    wxStaticText* GetStaticText352()
    {
	return m_staticText352;
    }
    wxSpinCtrl* GetLoopCount()
    {
	return m_loopCount;
    }
    wxStaticText* GetStaticText35()
    {
	return m_staticText35;
    }
    wxCheckBox* GetCbBreakOnError()
    {
	return m_cbBreakOnError;
    }
    wxPanel* GetPlLoop()
    {
	return m_plLoop;
    }
    wxStaticText* GetStaticText33()
    {
	return m_staticText33;
    }
    wxDirPickerCtrl* GetDirSelection()
    {
	return m_dirSelection;
    }
    wxPanel* GetPlDir()
    {
	return m_plDir;
    }
    wxListbook* GetLbTestCase()
    {
	return m_lbTestCase;
    }
    wxStaticLine* GetStaticLine43()
    {
	return m_staticLine43;
    }
    wxButton* GetBtCancel()
    {
	return m_btCancel;
    }
    wxButton* GetBtRun()
    {
	return m_btRun;
    }
    CncTestRunConfigBase(wxWindow* parent,
        wxWindowID id = wxID_ANY,
        const wxString& title = _("Cnc Test Run Configuration"),
        const wxPoint& pos = wxDefaultPosition,
        const wxSize& size = wxSize(500, 300),
        long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~CncTestRunConfigBase();
};

#endif
