//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxCrafterSecurityRun.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CNCGUICONTROLLER_CNCCONTROLERGUI_WXCRAFTERSECURITYRUN_BASE_CLASSES_H
#define _CNCGUICONTROLLER_CNCCONTROLERGUI_WXCRAFTERSECURITYRUN_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/statline.h>
#include <wx/button.h>
#include <wx/tglbtn.h>
#include <wx/timer.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class CncSecureRunBase : public wxDialog
{
protected:
    wxPanel* m_header1;
    wxStaticText* m_staticText6588;
    wxPanel* m_header2;
    wxStaticText* m_staticText65883;
    wxStaticLine* m_staticLine527312;
    wxPanel* m_remoteControl;
    wxStaticLine* m_staticLine52731;
    wxButton* m_btPlay;
    wxButton* m_btStop;
    wxStaticLine* m_staticLine52733;
    wxButton* m_btEmergengy;
    wxStaticLine* m_staticLine5273;
    wxStaticLine* m_staticLine6571;
    wxBitmapToggleButton* m_btViewTop;
    wxBitmapToggleButton* m_btViewBottom;
    wxBitmapToggleButton* m_btViewFront;
    wxBitmapToggleButton* m_btViewRear;
    wxBitmapToggleButton* m_btViewLeft;
    wxBitmapToggleButton* m_btViewRight;
    wxBitmapToggleButton* m_btViewIso1;
    wxBitmapToggleButton* m_btViewIso2;
    wxBitmapToggleButton* m_btViewIso3;
    wxBitmapToggleButton* m_btViewIso4;
    wxTimer* m_startupTimer;
    wxTimer* m_blinkTimer;

protected:
    virtual void initDialog(wxInitDialogEvent& event) { event.Skip(); }
    virtual void show(wxShowEvent& event) { event.Skip(); }
    virtual void onKeyDown(wxKeyEvent& event) { event.Skip(); }
    virtual void play(wxCommandEvent& event) { event.Skip(); }
    virtual void stop(wxCommandEvent& event) { event.Skip(); }
    virtual void emergengy(wxCommandEvent& event) { event.Skip(); }
    virtual void changeView(wxCommandEvent& event) { event.Skip(); }
    virtual void startupTimer(wxTimerEvent& event) { event.Skip(); }
    virtual void blinkTimer(wxTimerEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText6588() { return m_staticText6588; }
    wxPanel* GetHeader1() { return m_header1; }
    wxStaticText* GetStaticText65883() { return m_staticText65883; }
    wxPanel* GetHeader2() { return m_header2; }
    wxStaticLine* GetStaticLine527312() { return m_staticLine527312; }
    wxPanel* GetRemoteControl() { return m_remoteControl; }
    wxStaticLine* GetStaticLine52731() { return m_staticLine52731; }
    wxButton* GetBtPlay() { return m_btPlay; }
    wxButton* GetBtStop() { return m_btStop; }
    wxStaticLine* GetStaticLine52733() { return m_staticLine52733; }
    wxButton* GetBtEmergengy() { return m_btEmergengy; }
    wxStaticLine* GetStaticLine5273() { return m_staticLine5273; }
    wxStaticLine* GetStaticLine6571() { return m_staticLine6571; }
    wxBitmapToggleButton* GetBtViewTop() { return m_btViewTop; }
    wxBitmapToggleButton* GetBtViewBottom() { return m_btViewBottom; }
    wxBitmapToggleButton* GetBtViewFront() { return m_btViewFront; }
    wxBitmapToggleButton* GetBtViewRear() { return m_btViewRear; }
    wxBitmapToggleButton* GetBtViewLeft() { return m_btViewLeft; }
    wxBitmapToggleButton* GetBtViewRight() { return m_btViewRight; }
    wxBitmapToggleButton* GetBtViewIso1() { return m_btViewIso1; }
    wxBitmapToggleButton* GetBtViewIso2() { return m_btViewIso2; }
    wxBitmapToggleButton* GetBtViewIso3() { return m_btViewIso3; }
    wxBitmapToggleButton* GetBtViewIso4() { return m_btViewIso4; }
    wxTimer* GetStartupTimer() { return m_startupTimer; }
    wxTimer* GetBlinkTimer() { return m_blinkTimer; }
    CncSecureRunBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("CNC Secure Run"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(-1,-1), long style = wxSTAY_ON_TOP);
    virtual ~CncSecureRunBase();
};

#endif
